// Background service worker for NoAI YouTube Extension

const DEFAULT_SETTINGS = {
  enabled: true,
  action: 'tag', // 'tag' | 'hide' | 'blur'
  detectOfficialLabels: true,
  detectKeywords: true,
  detectChannelList: true,
  enableCuratedList: true,
  detectContentFarmPatterns: true,
  enableQuickBlockButton: true,
  customKeywords: [
    // Direct Tools, Music & Audio Generators
    'ai', 'suno', 'suno.ai', 'suno ai', 'suno v3', 'suno v4', 'suno v5', 'suno v6', 'suno studio',
    'udio', 'udio.ai', 'udio ai', 'udio v1', 'udio v1.5', 'udio v2',
    'elevenlabs', 'eleven labs', '11labs', 'fakeyou', 'uberduck', 'tortoise tts', 'rvc', 'rvc v2',
    'so-vits-svc', 'sovits', 'bark ai', 'voice clone', 'voice cloning', 'ai voice', 'ai vocals',
    'ai singer', 'ai cover', 'ai covers', 'ai duet', 'ai song', 'ai songs', 'ai rap', 'ai beat', 'ai beats',
    'ai track', 'ai tracks', 'ai audio', 'ai generated music', 'prompted music', 'riffusion', 'musicgen',
    // Celebrity / Character Voice Clones
    'ai drake', 'ai kanye', 'ai trump', 'ai biden', 'ai obama', 'ai spongebob', 'ai plankton',
    'ai michael jackson', 'ai freddie mercury', 'ai the weeknd', 'ai eminem', 'ai taylor swift',
    // Video, Animation & Diffusion
    'sora', 'sora 2', 'sora openai', 'runway', 'runwayml', 'gen-2', 'gen-3', 'gen-3 alpha', 'gen3 alpha',
    'kling', 'kling ai', 'kling 1.5', 'pika', 'pika labs', 'pika 1.0', 'pika 2.0', 'luma', 'luma ai',
    'dream machine', 'minimax', 'minimax video', 'hailuo', 'hailuo ai', 'haiper', 'haiper ai',
    'viggle', 'viggle ai', 'veo', 'google veo', 'ltx video', 'cogvideo', 'mochi 1', 'animatediff',
    'deforum', 'deforum stable diffusion', 'infinite zoom ai',
    'ai animation', 'ai animated', 'ai video', 'ai film', 'ai movie', 'ai cinema', 'ai trailer', 'ai visualizer',
    // Image & Art
    'midjourney', 'midjourney v5', 'midjourney v6', 'midjourney v7', 'dall-e', 'dall-e 3', 'dalle', 'dalle3',
    'stable diffusion', 'sdxl', 'sd1.5', 'sd3', 'flux.1', 'flux', 'flux dev', 'flux schnell',
    'comfyui', 'leonardo ai', 'ideogram', 'ideogram ai', 'magnific', 'magnific ai',
    'ai art', 'ai artwork', 'ai illustration',
    // Terminology & Disclosures
    'generative ai', 'gen ai', 'genai', 'ai generated', 'generated with ai', 'generated by ai',
    'made with ai', 'created with ai', 'created using ai', 'powered by ai', 'synthesized with ai',
    'deepfake', 'deep fake', 'synthetic media', 'synthetic voice', 'chatgpt', 'chat gpt', 'gpt-4', 'gpt-4o',
    'ai model', 'ai prompts', 'prompt sharing', 'prompt:', 'prompts shared',
    // Multilingual AI indicators
    'ki generiert', 'generado por ia', 'hecho con ia', 'généré par ia', 'создано ии', 'нейросеть',
    'ai生成', '画像生成ai', '音楽生成ai'
  ],
  customChannels: [],
  blockedCount: 0
};

chrome.runtime.onInstalled.addListener(async () => {
  const current = await chrome.storage.sync.get(null);
  const toSet = {};
  for (const [key, val] of Object.entries(DEFAULT_SETTINGS)) {
    if (current[key] === undefined) {
      toSet[key] = val;
    }
  }
  // Ensure default action is tag if not explicitly set
  if (!current.action) {
    toSet.action = 'tag';
  }
  if (Object.keys(toSet).length > 0) {
    await chrome.storage.sync.set(toSet);
  }
  console.log('NoAI for YouTube installed / updated.');
});

// Update extension icon badge count for the active tab
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.type === 'UPDATE_AI_COUNT' && sender.tab?.id) {
    const count = message.count || 0;
    const badgeText = count > 0 ? String(count) : '';
    chrome.action.setBadgeText({ tabId: sender.tab.id, text: badgeText });
    chrome.action.setBadgeBackgroundColor({ tabId: sender.tab.id, color: '#e11d48' });
    sendResponse({ ok: true });
  }
  return true;
});
