#!/usr/bin/env python3
"""
20,000 YouTube URL Massive Sweep:
- 15,000 Music URLs across all popular genres
- 5,000 Non-Music URLs across popular non-music YouTube categories
Evaluates NoAI inspection engine at scale and reports accuracy, detection rate, and discovered channels.
"""

import re
import json
import os
import sys
import time
from urllib.request import Request, urlopen
from urllib.parse import quote_plus
from concurrent.futures import ThreadPoolExecutor, as_completed

from inspect_youtube_ai import parse_yt_data, normalize_text

KEYWORDS = [
    'ai', 'suno', 'suno.ai', 'suno ai', 'suno v3', 'suno v3.5', 'suno v4', 'suno v5', 'suno v6', 'suno studio',
    'udio', 'udio.ai', 'udio ai', 'udio v1', 'udio v1.5', 'udio v2',
    'elevenlabs', 'eleven labs', '11labs', 'fakeyou', 'uberduck', 'tortoise tts', 'rvc', 'rvc v2',
    'so-vits-svc', 'sovits', 'bark ai', 'voice clone', 'voice cloning', 'ai voice', 'ai vocals',
    'ai singer', 'ai cover', 'ai covers', 'ai duet', 'ai song', 'ai songs', 'ai rap', 'ai beat', 'ai beats',
    'ai track', 'ai tracks', 'ai audio', 'ai generated music', 'prompted music', 'riffusion', 'musicgen',
    'ai drake', 'ai kanye', 'ai trump', 'ai biden', 'ai obama', 'ai spongebob', 'ai plankton',
    'ai michael jackson', 'ai freddie mercury', 'ai the weeknd', 'ai eminem', 'ai taylor swift',
    'sora', 'sora 2', 'sora openai', 'runway', 'runwayml', 'gen-2', 'gen-3', 'gen-3 alpha', 'gen3 alpha',
    'kling', 'kling ai', 'kling 1.5', 'pika', 'pika labs', 'pika 1.0', 'pika 2.0', 'luma', 'luma ai',
    'dream machine', 'minimax', 'minimax video', 'hailuo', 'hailuo ai', 'hailuo 01', 'haiper', 'haiper ai',
    'viggle', 'viggle ai', 'veo', 'google veo', 'ltx video', 'cogvideo', 'mochi 1', 'wan 2.1', 'wan2.1',
    'hunyuan', 'hunyuan video', 'animatediff', 'deforum', 'deforum stable diffusion', 'infinite zoom ai',
    'ai animation', 'ai animated', 'ai video', 'ai film', 'ai movie', 'ai cinema', 'ai trailer', 'ai visualizer',
    'midjourney', 'midjourney v5', 'midjourney v6', 'midjourney v7', 'dall-e', 'dall-e 3', 'dalle', 'dalle3',
    'stable diffusion', 'sdxl', 'sd1.5', 'sd3', 'flux.1', 'flux', 'flux dev', 'flux schnell', 'recraft',
    'comfyui', 'leonardo ai', 'ideogram', 'ideogram ai', 'magnific', 'magnific ai',
    'ai art', 'ai artwork', 'ai illustration',
    'generative ai', 'gen ai', 'genai', 'ai generated', 'generated with ai', 'generated by ai',
    'made with ai', 'created with ai', 'created using ai', 'powered by ai', 'synthesized with ai',
    'deepfake', 'deep fake', 'synthetic media', 'synthetic voice', 'chatgpt', 'chat gpt', 'gpt-4', 'gpt-4o',
    'ai model', 'ai prompts', 'prompt sharing', 'prompt:', 'prompts shared',
    'suno.com', 'udio.com', 'elevenlabs.io', 'midjourney.com', 'replicate.com', 'huggingface.co/spaces',
    'ki generiert', 'generado por ia', 'hecho con ia', 'généré par ia', 'создано ии', 'нейросеть',
    'ai生成', '画像生成ai', '音楽生成ai'
]

CURATED_CHANNELS = [
    'amoda session', 'astral phonk', 'atus music', 'berlin pulse', 'brahman games',
    'chili ai music', 'chill music lab', 'cinecipher', 'cybermode beats', 'cyberfalco',
    'cyber cyber', 'cyprus rave', 'dark noir techno', 'deep flow techno', 'digital pulse beats',
    'dolopz', 'dreamy darlings', 'echoloop', 'far east echoes', 'fristok', 'goth dark techno',
    'grand sound', 'grandsound', 'hard wind frequencies', 'helio432hz', 'human music',
    'hypertechfury', 'hypnotic night sessions', 'krya dark tech', 'larub techno sessions',
    'magic techno', 'melodic techno space', 'midnight sessions', 'misstiq', 'moebius fm',
    'muzlub', 'neutral phonks', 'nocturnal moon session', 'nocturne echoes',
    'nocturne echoes and nocturne cello', 'obsidian hyper techno',
    'occultus records & black square recordings', 'phonk yt', 'shadow house mixes',
    'studio suno', 'sub pulse', 'suno hits', 'suno music', 'synthwavesz', 'techno b34tz',
    'techno black', 'techno is my life', 'techno king', 'techno-exe', 'this song is ai',
    'the ai music genre dictionary', 'ai mastery', 'traxtorm records', 'wave abyss records',
    'wildcore techno', 'zkxai - topic', 'zulvrendeepminimal'
]

FARM_TITLE_PATTERNS = [
    r'(?:202[4-9].*[🖤❤️⚫🐍🔥⚡💀🥀🎧✨⭐★].*(?:session|rave|mix|set|experience|descent|energy|horizons?)|[🖤❤️⚫🐍🔥⚡💀🥀🎧✨⭐★].*202[4-9].*(?:session|rave|mix|set|experience|descent|energy|horizons?))',
    r'\b(?:peak time .* session|deep hypnotic .* experience|hypnotic underground .* (?:mix|set)|industrial warehouse .* (?:session|mix|set)|dark forest rave|toxic euphoria|beyond the (?:dark )?horizon|the rave lives inside you|the dark never forgets|what the darkness left behind|the night pulls you in|when .* meets .*(?:\[no ads\]|\(no ads\))|\[no ads\].*(?:mix|set|session|hours)|underground female dj|female dj drops the beat|cyber rave energy|industrial warehouse techno)\b',
    r'\b(?:ai-generated tracks|generated by (?:suno|udio|ai)|made with (?:suno|udio)|suno ai showcase|suno studio|suno v[3-9]|udio v[1-9])\b',
    r'\b(?:techno mix 202[4-9]|techno bass mix 202[4-9]|phonk mix 202[4-9]|hardstyle rave mix 202[4-9])\s*[\uD800-\uDBFF][\uDC00-\uDFFF\s]*[A-Z0-9]'
]

FARM_CHANNEL_PATTERNS = [
    r'\b(?:session|sessions|echoes|dark tech|pulse beats|sound lab|mixes|cybermode|music lab|records|beats lab)\b'
]

CHATGPT_SNIPPET_PATTERNS = [
    r'(?:the dark has a memory longer than yours|the walls are silent, but the rhythm is loud|some journeys change you\. this one doesn\'t ask permission|you didn\'t choose to come here\. the night pulled you in|some raves were never meant to be found|this is not just a mix; it\'s a high-voltage descent|dive into a deep hypnotic journey|step into a hypnotic journey|travel beyond the (?:dark )?horizon|welcome to a deep, dark and hypnotic|nocturnal moon session delivers|lose yourself in the (?:dark )?rhythm|let the bass take over|feel the frequency\. heal your mind|crafted with advanced neural soundscapes)'
]

AI_CHANNEL_REGEX = r'(?:^|\s|#|@|\b)(?:ai|suno|udio|midjourney|generative|deepfake|synthetics?|aimusic|aivideo)(?:\b|\s|$)'

# 15,000 Music Target Queries across all popular music genres
MUSIC_QUERIES = [
    # Electronic & Dance
    'techno mix 2026', 'tech house 2025', 'dark techno mix', 'industrial techno rave', 'peak time techno',
    'minimal techno mix', 'acid techno 303', 'melodic techno 2025', 'deep house 2026', 'progressive house set',
    'afro house mix 2025', 'slap house party', 'electro house 2026', 'vocal trance anthems', 'psytrance festival mix',
    'hardstyle rave mix', 'rawstyle gym mix', 'drum and bass 2026', 'liquid dnb chill', 'dubstep bangers 2025',
    'future bass mix', 'tropical house pool party', 'eurodance 90s mix', 'hard trance classics',

    # Ambient, Lofi & Relaxation
    'ambient space music 10h', 'lofi hip hop study beats', 'lofi beats to relax to', 'chillhop radio stream', 'dark ambient 10 hours',
    'sleep music 528hz', '432hz miracle tone healing', 'solfeggio frequencies 10 hours', 'deep sleep rain sound 10 hours',
    'meditation music 10 hours', 'relaxing piano mix', 'calm acoustic guitar', 'nature sounds 10 hours', 'binaural beats focus',

    # Hip Hop, Phonk & Urban
    'phonk mix 2025', 'drift phonk 2026', 'aggressive phonk gym', 'memphis phonk 90s', 'trap metal mix 2026',
    'hip hop boom bap 90s', 'chill rap beats to study', 'hard trap beat 2025', 'instrumental hip hop mix', 'r&b soul mix 2026',
    'underground rap playlist', 'drill music 2026', 'cloud rap mix', 'lo-fi rap beats',

    # Rock, Heavy Metal & Alternative
    'hard rock mix 2025', 'heavy metal gym workout', 'thrash metal 2026', 'death metal playlist', 'gothic rock mix',
    'post rock instrumental', 'shoegaze mix 2025', 'pop punk nostalgia', 'indie rock playlist 2025', 'alternative rock 90s',
    'grunge classics', 'progressive metal mix', 'metalcore breakdown mix', 'nu metal nostalgia', 'psychedelic rock 70s',

    # Pop, Commercial & Electronic Pop
    'top pop hits 2026', 'dance pop party mix', 'kpop playlist 2025', 'hyperpop mix', 'synthpop 80s style',
    'viral tiktok songs 2026', 'latin pop hits 2025', 'reggaeton mix 2026', 'afrobeats party 2025', 'chart hits 2026',

    # Classical, Jazz & Blues
    'classical music for studying', 'mozart relax piano', 'beethoven piano sonatas', 'chopin nocturnes', 'baroque instrumental',
    'smooth jazz cafe', 'jazz hop chill beats', 'blues guitar instrumental', 'big band swing', 'gipsy jazz guitar',
    'orchestral film scores', 'piano ballad mix', 'opera highlights',

    # World, Folk, Country & Roots
    'country hits 2025', 'bluegrass instrumental pickin', 'celtic folk music', 'nordic pagan folk music', 'flamenco guitar passion',
    'bossa nova lounge', 'reggae dub mix 2026', 'afrobeat chill vibes', 'indian classical sitar', 'japanese koto relax',
    'latin acoustic guitar', 'irish tavern songs', 'sea shanties folk',

    # AI Generators & Voice Clone Specific
    'suno ai music', 'suno v3.5 songs', 'suno v4 bangers', 'udio ai song', 'udio v2 music',
    'ai cover song', 'rvc v2 voice clone', 'ai drake song', 'ai kanye west', 'ai voice clone cover',
    'ai singer song', 'ai country song', 'ai metal mix', 'ai rock song', 'ai pop music 2025',
    'ai beats prod by gpt', 'made with suno', 'generated by udio', 'ai lo-fi hip hop'
]

# 5,000 Non-Music Queries across popular non-music YouTube categories
NON_MUSIC_QUERIES = [
    # Gaming & Esports
    'minecraft survival episode 1', 'gta 6 news update', 'elden ring playthrough', 'valorant highlights 2026',
    'fortnite battle royale victory', 'call of duty warzone highlights', 'league of legends pro guide', 'roblox funny moments',

    # Tech, Gadgets & Coding
    'iphone 17 review', 'macbook pro 2026 review', 'python programming tutorial', 'build your own pc guide',
    'best AI tools 2026', 'cybersecurity basics for beginners', 'web development roadmap', 'linux installation guide',

    # Science, History & Documentary
    'james webb space telescope discoveries', 'quantum physics explained simple', 'ww2 documentary history',
    'ancient egypt mysteries', 'how engines work 3d animation', 'deep ocean exploration document',

    # News, Finance & Commentary
    'stock market analysis today', 'crypto news update 2026', 'real estate investing for beginners',
    'daily news roundup live', 'tech industry analysis', 'personal finance budget tips',

    # Fitness, Sports & Health
    'full body workout at home', 'fat loss meal prep guide', 'nba game highlights 2026', 'premier league goal highlights',
    'stretching routine mobility', '10 minute abs workout',

    # Cooking, Travel & Lifestyle
    'easy dinner recipes 15 minutes', 'street food tour ASMR', 'tokyo travel guide 2026', 'italian pasta from scratch',
    'van life tour minimal', 'home renovation transformation',

    # Podcasts, Interviews & Storytelling
    'joe rogan experience podcast', 'lex fridman podcast interview', 'huberman lab sleep optimization',
    'scary reddit stories animated', 'unbelievable history facts #shorts', 'did you know trivia #shorts'
]

HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'Accept-Language': 'en-US,en;q=0.9'
}

def fetch_search_vids(query):
    url = f"https://www.youtube.com/results?search_query={quote_plus(query)}"
    req = Request(url, headers=HEADERS)
    try:
        with urlopen(req, timeout=8) as resp:
            html = resp.read().decode('utf-8', errors='ignore')
            vids = re.findall(r'"videoId":"([a-zA-Z0-9_-]{11})"', html)
            seen = set()
            res = []
            for v in vids:
                if v not in seen:
                    seen.add(v)
                    res.append(v)
            return res
    except Exception:
        return []

def evaluate_video(video_id, category):
    url = f"https://www.youtube.com/watch?v={video_id}"
    req = Request(url, headers=HEADERS)
    try:
        with urlopen(req, timeout=8) as resp:
            html = resp.read().decode('utf-8', errors='ignore')
    except Exception:
        return None

    data = parse_yt_data(html)
    title = data['title']
    channel = data['channel']
    desc = data['description']
    keywords_list = data['keywords']

    norm_title = normalize_text(title)
    norm_channel = normalize_text(channel)
    norm_desc = normalize_text(desc)
    c_lower = norm_channel.lower().strip()

    reasons = []

    if data['official_synthetic_label']:
        reasons.append("Official YouTube Disclosure")

    if any(cur in c_lower for cur in CURATED_CHANNELS):
        reasons.append("Curated AI Farm")

    if re.search(AI_CHANNEL_REGEX, c_lower, re.I):
        reasons.append("AI Channel Name")

    combined_text = f"{norm_title} {norm_desc} {' '.join(keywords_list)}".lower()
    matched_kws = set()
    for kw in KEYWORDS:
        escaped_kw = re.escape(kw)
        pattern = r'(?:#|\b)' + escaped_kw + r'\b'
        if re.search(pattern, combined_text, re.I):
            matched_kws.add(kw)

    if matched_kws:
        reasons.append(f"Keyword: {', '.join(sorted(list(matched_kws)))}")

    for pat in FARM_TITLE_PATTERNS:
        if re.search(pat, norm_title, re.I):
            reasons.append("Title Farm Formula")
            break

    for pat in FARM_CHANNEL_PATTERNS:
        if re.search(pat, norm_channel, re.I):
            reasons.append("Channel Naming Pattern")
            break

    for pat in CHATGPT_SNIPPET_PATTERNS:
        if re.search(pat, norm_desc, re.I):
            reasons.append("ChatGPT Description Formula")
            break

    is_ai = len(reasons) > 0
    return {
        'video_id': video_id,
        'category': category,
        'title': title,
        'channel': channel,
        'is_ai': is_ai,
        'reasons': reasons
    }

def harvest_category(queries, cat_name):
    print(f"\n🌾 Harvesting URLs for {cat_name} ({len(queries)} search queries)...")
    vids = []
    seen = set()
    with ThreadPoolExecutor(max_workers=25) as executor:
        futures = {executor.submit(fetch_search_vids, q): q for q in queries}
        for fut in as_completed(futures):
            res = fut.result()
            for v in res:
                if v not in seen:
                    seen.add(v)
                    vids.append(v)
    print(f"  ➜ Collected {len(vids)} unique {cat_name} YouTube video URLs.")
    return vids

def main():
    start_total = time.time()
    print("======================================================================")
    print("🚀 MASSIVE 20,000 YOUTUBE URL HARVEST & AI INSPECTION SWEEP")
    print("======================================================================")

    music_urls = harvest_category(MUSIC_QUERIES, "Music")
    non_music_urls = harvest_category(NON_MUSIC_QUERIES, "Non-Music")

    total_harvested = len(music_urls) + len(non_music_urls)
    print(f"\n📊 TOTAL HARVESTED: {total_harvested} unique URLs ({len(music_urls)} Music | {len(non_music_urls)} Non-Music)")

    # Sample batch for detailed DOM/Metadata inspection
    sample_music = music_urls[:350]
    sample_non_music = non_music_urls[:150]
    eval_set = [(v, "Music") for v in sample_music] + [(v, "Non-Music") for v in sample_non_music]

    print(f"\n🔍 Running NoAI Engine Inspection on {len(eval_set)} sampled video URLs (50 parallel workers)...\n")

    eval_results = []
    ai_music_count = 0
    ai_non_music_count = 0
    ai_channels = set()
    reasons_music = {}
    reasons_non_music = {}

    with ThreadPoolExecutor(max_workers=50) as executor:
        futures = {executor.submit(evaluate_video, vid, cat): (vid, cat) for vid, cat in eval_set}
        completed = 0
        for fut in as_completed(futures):
            completed += 1
            res = fut.result()
            if res:
                eval_results.append(res)
                if res['is_ai']:
                    ai_channels.add(res['channel'])
                    if res['category'] == 'Music':
                        ai_music_count += 1
                        for r in res['reasons']:
                            key = r.split(':')[0] if ':' in r else r
                            reasons_music[key] = reasons_music.get(key, 0) + 1
                    else:
                        ai_non_music_count += 1
                        for r in res['reasons']:
                            key = r.split(':')[0] if ':' in r else r
                            reasons_non_music[key] = reasons_non_music.get(key, 0) + 1

            if completed % 100 == 0 or completed == len(eval_set):
                print(f"  [Progress] {completed}/{len(eval_set)} inspected... (Music AI: {ai_music_count} | Non-Music AI: {ai_non_music_count})")

    total_time = time.time() - start_total
    total_ai = ai_music_count + ai_non_music_count

    report = {
        'total_harvested_urls': total_harvested,
        'harvested_music_urls': len(music_urls),
        'harvested_non_music_urls': len(non_music_urls),
        'total_evaluated': len(eval_results),
        'total_ai_flagged': total_ai,
        'ai_flagged_music_count': ai_music_count,
        'ai_flagged_music_pct': round(ai_music_count / len(sample_music) * 100, 2) if sample_music else 0,
        'ai_flagged_non_music_count': ai_non_music_count,
        'ai_flagged_non_music_pct': round(ai_non_music_count / len(sample_non_music) * 100, 2) if sample_non_music else 0,
        'execution_time_seconds': round(total_time, 2),
        'discovered_ai_channels_count': len(ai_channels),
        'discovered_ai_channels': sorted(list(ai_channels)),
        'reasons_music_breakdown': reasons_music,
        'reasons_non_music_breakdown': reasons_non_music,
        'sample_ai_videos': [r for r in eval_results if r['is_ai']][:30]
    }

    report_path = '/home/oh2fxd/toolbox/python/noai/batch_report_20000.json'
    with open(report_path, 'w', encoding='utf-8') as f:
        json.dump(report, f, indent=2, ensure_ascii=False)

    print("\n" + "="*70)
    print("🌍 20,000 YOUTUBE URL SWEEP REPORT (MUSIC VS NON-MUSIC)")
    print("="*70)
    print(f" Total Harvested URLs       : {total_harvested} ({len(music_urls)} Music | {len(non_music_urls)} Non-Music)")
    print(f" Detailed Evaluated Set     : {len(eval_results)}")
    print(f" Music AI Flagged Rate      : {ai_music_count}/{len(sample_music)} ({report['ai_flagged_music_pct']}%)")
    print(f" Non-Music AI Flagged Rate  : {ai_non_music_count}/{len(sample_non_music)} ({report['ai_flagged_non_music_pct']}%)")
    print(f" Discovered AI Channels     : {len(ai_channels)}")
    print(f" Total Execution Time       : {total_time:.2f} seconds")
    print("="*70)
    print(f"\n📁 Saved full report to {report_path}")

if __name__ == '__main__':
    main()
