#!/usr/bin/env python3
"""
50-Genre YouTube AI Detection Inspection Sweep
Harvests and evaluates YouTube videos across 50 distinct genres using NoAI's updated FP-free detection engine.
"""

import re
import json
import os
import sys
import time
from urllib.request import Request, urlopen
from urllib.parse import quote_plus
from concurrent.futures import ThreadPoolExecutor, as_completed

# Define 50 distinct genres
GENRES = [
    # Electronic & Dance
    "Techno", "Tech House", "Deep House", "Progressive House", "Afro House",
    "Trance", "Psytrance", "Hardstyle", "Drum and Bass", "Dubstep",
    "Electro Pop", "Synthwave", "Cyberpunk", "Eurodance", "EDM Mainstage",

    # Ambient, Chill & Relaxation
    "Lofi Hip Hop", "Dark Ambient", "Meditation 528Hz", "Relaxing Piano", "Nature Sounds",
    "Chillhop", "Binaural Beats", "ASMR", "Space Ambient", "Solfeggio Frequencies",

    # Hip Hop, Urban & Phonk
    "Drift Phonk", "Memphis Phonk", "Boom Bap Hip Hop", "Trap Metal", "Modern Trap",
    "Cloud Rap", "R&B Soul", "Drill", "Underground Rap", "Instrumental Hip Hop",

    # Rock, Metal & Alternative
    "Heavy Metal", "Thrash Metal", "Gothic Rock", "Post Rock", "Shoegaze",
    "Pop Punk", "Indie Rock", "Progressive Metal", "Alternative Rock", "Hard Rock",

    # Classical, Jazz & World
    "Classical Piano", "Baroque Orchestra", "Smooth Jazz", "Bossa Nova", "Nordic Pagan Folk",
    "Celtic Folk", "Flamenco Guitar", "Afrobeat", "Indian Classical Sitar", "Reggae Dub",

    # AI Generators & Synthetic Media
    "AI Drake Voice Clones", "Suno AI Music", "Udio AI Songs", "AI Covers", "ChatGPT Music Farms"
]

# Updated FP-free detection keywords
KEYWORDS = [
    'suno', 'suno.ai', 'suno ai', 'suno v3', 'suno v3.5', 'suno v4', 'suno v5', 'suno v6', 'suno studio',
    'udio', 'udio.ai', 'udio ai', 'udio v1', 'udio v1.5', 'udio v2',
    'elevenlabs', 'eleven labs', '11labs', 'fakeyou', 'uberduck', 'tortoise tts', 'rvc', 'rvc v2',
    'so-vits-svc', 'sovits', 'bark ai', 'voice clone', 'voice cloning', 'ai voice', 'ai vocals',
    'ai singer', 'ai cover', 'ai covers', 'ai duet', 'ai song', 'ai songs', 'ai rap', 'ai beat', 'ai beats',
    'ai track', 'ai tracks', 'ai audio', 'ai generated music', 'ai generated song', 'prompted music', 'riffusion', 'musicgen',
    'ai drake', 'ai kanye', 'ai trump', 'ai biden', 'ai obama', 'ai spongebob', 'ai plankton',
    'ai michael jackson', 'ai freddie mercury', 'ai the weeknd', 'ai eminem', 'ai taylor swift',
    'sora 2', 'sora openai', 'sora ai', 'runwayml', 'gen-2', 'gen-3', 'gen-3 alpha', 'gen3 alpha',
    'kling ai', 'kling 1.5', 'pika labs', 'pika 1.0', 'pika 2.0', 'luma ai', 'luma dream machine',
    'minimax video', 'minimax ai', 'hailuo ai', 'hailuo 01', 'haiper ai', 'viggle ai', 'google veo', 'veo google',
    'ltx video', 'cogvideo', 'mochi 1', 'wan 2.1', 'wan2.1', 'hunyuan video', 'animatediff',
    'deforum stable diffusion', 'infinite zoom ai',
    'ai animation', 'ai animated video', 'ai film', 'ai movie', 'ai cinema', 'ai trailer', 'ai visualizer',
    'midjourney v5', 'midjourney v6', 'midjourney v7', 'dall-e 3', 'dalle3',
    'stable diffusion', 'sdxl', 'sd1.5', 'sd3', 'flux.1', 'flux dev', 'flux schnell', 'recraft',
    'comfyui', 'leonardo ai', 'ideogram ai', 'magnific ai',
    'ai art generator', 'ai artwork generator', 'ai illustration generator',
    'generative ai music', 'ai generated video', 'ai generated track',
    'generated with ai', 'generated by ai', 'made with ai', 'created with ai', 'created using ai',
    'powered by ai', 'synthesized with ai', 'synthetic media', 'synthetic voice',
    'ai model prompt', 'prompts shared',
    'suno.com', 'udio.com', 'elevenlabs.io', 'midjourney.com', 'replicate.com/spaces',
    'ki generiert', 'generado por ia', 'hecho con ia', 'généré par ia', 'создано ии', 'нейросеть',
    'ai生成', '画像生成ai', '音楽生成ai'
]

CURATED_AI_CHANNELS = [
    'amoda session', 'astral phonk', 'atus music', 'berlin pulse', 'brahman games',
    'chili ai music', 'chill music lab', 'cinecipher', 'cybermode beats', 'cyberfalco',
    'cyber cyber', 'cyprus rave', 'dark noir techno', 'deep flow techno', 'digital pulse beats',
    'dolopz', 'dreamy darlings', 'echoloop', 'far east echoes', 'fristok', 'goth dark techno',
    'grand sound', 'grandsound', 'hard wind frequencies', 'helio432hz', 'human music',
    'hypertechfury', 'hypnotic night sessions', 'krya dark tech', 'larub techno sessions',
    'magic techno', 'melodic techno space', 'midnight sessions', 'misstiq', 'moebius fm',
    'muzlub', 'neutral phonks', 'nocturnal moon session', 'nocturne echoes',
    'nocturne echoes and nocturne cello', 'obsidian hyper techno',
    'occultus records & black square recordings', 'phonk yt', 'shadow house mixes',
    'studio suno', 'sub pulse', 'suno hits', 'suno music', 'synthwavesz', 'techno b34tz',
    'techno black', 'techno is my life', 'techno king', 'techno-exe', 'this song is ai',
    'the ai music genre dictionary', 'ai mastery', 'traxtorm records', 'wave abyss records',
    'wildcore techno', 'zkxai - topic', 'zulvrendeepminimal'
]

AI_CHANNEL_REGEX = re.compile(
    r'(?:^|\s|#|@|\b)(?:suno\s*ai|udio\s*ai|ai\s*covers?|ai\s*music|ai\s*tracks?|ai\s*beats?|ai\s*generated|generative\s*ai\s*music|aimusic)(?:\b|\s|$)',
    re.I
)

FARM_TITLE_PATTERNS = [
    re.compile(r'(?:[🖤❤️⚫🐍🔥⚡💀🥀🎧✨⭐★]{2,}.*(?:session|rave|mix|set|experience|descent|energy|horizons?))', re.I),
    re.compile(r'\b(?:peak time .* session|deep hypnotic .* experience|hypnotic underground .* (?:mix|set)|industrial warehouse .* (?:session|mix|set)|dark forest rave|toxic euphoria|beyond the (?:dark )?horizon|the rave lives inside you|the dark never forgets|what the darkness left behind|the night pulls you in|underground female dj|female dj drops the beat|cyber rave energy)\b', re.I),
    re.compile(r'\b(?:ai-generated tracks|generated by (?:suno|udio)|made with (?:suno|udio)|suno ai showcase|suno studio|suno v[3-9]|udio v[1-9])\b', re.I)
]

FARM_CHANNEL_PATTERNS = [
    re.compile(r'\b(?:dark tech|cybermode|beats lab|techno-exe)\b', re.I),
    re.compile(r'\b(?:dark techno|deep techno|phonk|lofi|ai music|suno|udio)\s*-\s*topic\b', re.I)
]

CHATGPT_SNIPPET_PATTERNS = [
    re.compile(r'(?:the dark has a memory longer than yours|the walls are silent, but the rhythm is loud|some journeys change you\. this one doesn\'t ask permission|you didn\'t choose to come here\. the night pulled you in|some raves were never meant to be found|this is not just a mix; it\'s a high-voltage descent|dive into a deep hypnotic journey|step into a hypnotic journey|travel beyond the (?:dark )?horizon|welcome to a deep, dark and hypnotic|nocturnal moon session delivers|lose yourself in the (?:dark )?rhythm|let the bass take over|feel the frequency\. heal your mind|crafted with advanced neural soundscapes)', re.I)
]

def compile_keyword_regex():
    escaped = []
    for k in KEYWORDS:
        k = k.strip()
        if not k: continue
        bare = k[1:] if k.startswith('#') else k
        esc = re.escape(bare)
        escaped.append(rf'(?:#|\b){esc}\b')
    pattern = '|'.join(escaped)
    return re.compile(rf'({pattern})', re.I)

keyword_regex = compile_keyword_regex()

def harvest_urls_for_genre(genre):
    encoded = quote_plus(f"{genre} mix")
    url = f"https://www.youtube.com/results?search_query={encoded}"
    req = Request(url, headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0 Safari/537.36', 'Accept-Language': 'en-US,en;q=0.9'})
    urls = []
    try:
        with urlopen(req, timeout=12) as resp:
            html = resp.read().decode('utf-8', errors='ignore')
            found = re.findall(r'/watch\?v=([a-zA-Z0-9_-]{11})', html)
            seen = set()
            for v_id in found:
                if v_id not in seen:
                    seen.add(v_id)
                    urls.append(v_id)
    except Exception as e:
        print(f"  ❌ Failed harvesting for {genre}: {e}")
    return genre, urls

def inspect_video(video_id, genre):
    url = f"https://www.youtube.com/watch?v={video_id}"
    req = Request(url, headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0 Safari/537.36', 'Accept-Language': 'en-US,en;q=0.9'})
    try:
        with urlopen(req, timeout=10) as resp:
            html = resp.read().decode('utf-8', errors='ignore')
            
            # Extract title
            t_match = re.search(r'<title>(.*?)</title>', html)
            title = t_match.group(1).replace(' - YouTube', '').strip() if t_match else ''
            
            # Extract channel name
            c_match = re.search(r'"author":"([^"]+)"', html) or re.search(r'itemprop="author"[^>]*content="([^"]+)"', html)
            channel = c_match.group(1).strip() if c_match else ''
            
            # Extract description snippet
            d_match = re.search(r'"shortDescription":"([^"]+)"', html)
            desc = d_match.group(1).encode('utf-8').decode('unicode-escape', errors='ignore') if d_match else ''
            
            # Check for YouTube official disclosure label in HTML
            is_official_ai = False
            if 'synthetic' in html.lower() or 'altered' in html.lower() or 'made with ai' in html.lower():
                is_official_ai = True
                
            # Perform detection check
            is_ai, reason = check_card(title, channel, desc=desc, official_label=is_official_ai)
            return {
                "id": video_id,
                "genre": genre,
                "title": title,
                "channel": channel,
                "is_ai": is_ai,
                "reason": reason,
                "url": url
            }
    except Exception as e:
        return None

def check_card(title, channel, desc='', official_label=False):
    channel_lower = channel.lower()
    
    # 1. Curated list
    for known in CURATED_AI_CHANNELS:
        if known in channel_lower:
            return True, 'Curated AI Farm'
            
    # 2. AI Channel regex
    if AI_CHANNEL_REGEX.search(channel):
        return True, 'AI Channel'
        
    # 3. Official Disclosure
    if official_label:
        return True, 'YouTube AI Disclosure'
        
    # 4. Keyword search
    combined = f"{title} {desc}"
    m = keyword_regex.search(combined)
    if m:
        found = m.group(1) or m.group(0)
        return True, f"Keyword: {found.strip().upper()}"
        
    # 5. Content farm heuristic
    score = 0
    for tp in FARM_TITLE_PATTERNS:
        if tp.search(title):
            score += 30
            break
            
    for cp in FARM_CHANNEL_PATTERNS:
        if cp.search(channel):
            score += 25
            break
            
    if desc:
        for sp in CHATGPT_SNIPPET_PATTERNS:
            if sp.search(desc):
                score += 40
                break
                
    if score >= 50:
        return True, f'AI Farm Heuristic (score={score})'
        
    return False, 'Legitimate'

def main():
    start_time = time.time()
    print(f"🚀 Starting 50-Genre YouTube AI Inspection Sweep across {len(GENRES)} genres...")
    
    # Step 1: Harvest URLs per genre
    print("\n--- STEP 1: Harvesting Video URLs for 50 Genres ---")
    genre_url_map = {}
    with ThreadPoolExecutor(max_workers=20) as executor:
        futures = [executor.submit(harvest_urls_for_genre, g) for g in GENRES]
        for f in as_completed(futures):
            g, urls = f.result()
            genre_url_map[g] = urls
            print(f"  • {g:30s}: Harvested {len(urls)} videos")
            
    all_tasks = []
    for g, urls in genre_url_map.items():
        for vid in urls:
            all_tasks.append((vid, g))
            
    total_videos = len(all_tasks)
    print(f"\nTotal Unique Videos Harvested across 50 Genres: {total_videos}")
    
    # Step 2: Inspect and evaluate videos in parallel
    print("\n--- STEP 2: Inspecting and Evaluating Video Metadata ---")
    evaluated_results = []
    ai_flagged_count = 0
    genre_stats = {g: {"total": 0, "ai_count": 0, "ai_pct": 0.0} for g in GENRES}
    
    completed = 0
    with ThreadPoolExecutor(max_workers=30) as executor:
        futures = [executor.submit(inspect_video, vid, g) for vid, g in all_tasks]
        for f in as_completed(futures):
            res = f.result()
            completed += 1
            if completed % 100 == 0 or completed == total_videos:
                print(f"  Inspected {completed}/{total_videos} videos ({(completed/total_videos)*100:.1f}%)...")
            if res:
                evaluated_results.append(res)
                g = res["genre"]
                genre_stats[g]["total"] += 1
                if res["is_ai"]:
                    ai_flagged_count += 1
                    genre_stats[g]["ai_count"] += 1

    for g in GENRES:
        t = genre_stats[g]["total"]
        a = genre_stats[g]["ai_count"]
        genre_stats[g]["ai_pct"] = round((a / t * 100), 2) if t > 0 else 0.0
        
    elapsed = round(time.time() - start_time, 2)
    
    report = {
        "total_genres": len(GENRES),
        "total_videos_inspected": len(evaluated_results),
        "total_ai_flagged": ai_flagged_count,
        "overall_ai_pct": round((ai_flagged_count / len(evaluated_results) * 100), 2) if evaluated_results else 0.0,
        "elapsed_seconds": elapsed,
        "genre_stats": genre_stats,
        "ai_flagged_samples": [r for r in evaluated_results if r["is_ai"]]
    }
    
    output_path = "/home/oh2fxd/toolbox/python/noai/batch_report_50_genres.json"
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)
        
    print(f"\n==================================================")
    print(f"SWEEP COMPLETE in {elapsed}s!")
    print(f"Total Genres Tested: {len(GENRES)}")
    print(f"Total Videos Inspected: {len(evaluated_results)}")
    print(f"Total AI Flagged: {ai_flagged_count} ({report['overall_ai_pct']}%)")
    print(f"Saved full report to: {output_path}")

if __name__ == "__main__":
    main()
