#!/usr/bin/env python3
"""
5000-Video Multi-Genre YouTube AI Detection Inspection
Scans thousands of YouTube URLs across all major music genres and content styles
to evaluate AI detection performance and discover AI content farms.
"""

import re
import json
import os
import sys
import time
from urllib.request import Request, urlopen
from urllib.parse import quote_plus
from concurrent.futures import ThreadPoolExecutor, as_completed

from inspect_youtube_ai import parse_yt_data, normalize_text

KEYWORDS = [
    'ai', 'suno', 'suno.ai', 'suno ai', 'suno v3', 'suno v3.5', 'suno v4', 'suno v5', 'suno v6', 'suno studio',
    'udio', 'udio.ai', 'udio ai', 'udio v1', 'udio v1.5', 'udio v2',
    'elevenlabs', 'eleven labs', '11labs', 'fakeyou', 'uberduck', 'tortoise tts', 'rvc', 'rvc v2',
    'so-vits-svc', 'sovits', 'bark ai', 'voice clone', 'voice cloning', 'ai voice', 'ai vocals',
    'ai singer', 'ai cover', 'ai covers', 'ai duet', 'ai song', 'ai songs', 'ai rap', 'ai beat', 'ai beats',
    'ai track', 'ai tracks', 'ai audio', 'ai generated music', 'prompted music', 'riffusion', 'musicgen',
    'ai drake', 'ai kanye', 'ai trump', 'ai biden', 'ai obama', 'ai spongebob', 'ai plankton',
    'ai michael jackson', 'ai freddie mercury', 'ai the weeknd', 'ai eminem', 'ai taylor swift',
    'sora', 'sora 2', 'sora openai', 'runway', 'runwayml', 'gen-2', 'gen-3', 'gen-3 alpha', 'gen3 alpha',
    'kling', 'kling ai', 'kling 1.5', 'pika', 'pika labs', 'pika 1.0', 'pika 2.0', 'luma', 'luma ai',
    'dream machine', 'minimax', 'minimax video', 'hailuo', 'hailuo ai', 'hailuo 01', 'haiper', 'haiper ai',
    'viggle', 'viggle ai', 'veo', 'google veo', 'ltx video', 'cogvideo', 'mochi 1', 'wan 2.1', 'wan2.1',
    'hunyuan', 'hunyuan video', 'animatediff', 'deforum', 'deforum stable diffusion', 'infinite zoom ai',
    'ai animation', 'ai animated', 'ai video', 'ai film', 'ai movie', 'ai cinema', 'ai trailer', 'ai visualizer',
    'midjourney', 'midjourney v5', 'midjourney v6', 'midjourney v7', 'dall-e', 'dall-e 3', 'dalle', 'dalle3',
    'stable diffusion', 'sdxl', 'sd1.5', 'sd3', 'flux.1', 'flux', 'flux dev', 'flux schnell', 'recraft',
    'comfyui', 'leonardo ai', 'ideogram', 'ideogram ai', 'magnific', 'magnific ai',
    'ai art', 'ai artwork', 'ai illustration',
    'generative ai', 'gen ai', 'genai', 'ai generated', 'generated with ai', 'generated by ai',
    'made with ai', 'created with ai', 'created using ai', 'powered by ai', 'synthesized with ai',
    'deepfake', 'deep fake', 'synthetic media', 'synthetic voice', 'chatgpt', 'chat gpt', 'gpt-4', 'gpt-4o',
    'ai model', 'ai prompts', 'prompt sharing', 'prompt:', 'prompts shared',
    'ki generiert', 'generado por ia', 'hecho con ia', 'généré par ia', 'создано ии', 'нейросеть',
    'ai生成', '画像生成ai', '音楽生成ai'
]

CURATED_CHANNELS = [
    'amoda session', 'astral phonk', 'atus music', 'berlin pulse', 'brahman games',
    'chili ai music', 'chill music lab', 'cinecipher', 'cybermode beats', 'cyberfalco',
    'cyber cyber', 'cyprus rave', 'dark noir techno', 'deep flow techno', 'digital pulse beats',
    'dolopz', 'dreamy darlings', 'echoloop', 'far east echoes', 'fristok', 'goth dark techno',
    'grand sound', 'grandsound', 'hard wind frequencies', 'helio432hz', 'human music',
    'hypertechfury', 'hypnotic night sessions', 'krya dark tech', 'larub techno sessions',
    'magic techno', 'melodic techno space', 'midnight sessions', 'misstiq', 'moebius fm',
    'muzlub', 'neutral phonks', 'nocturnal moon session', 'nocturne echoes',
    'nocturne echoes and nocturne cello', 'obsidian hyper techno',
    'occultus records & black square recordings', 'phonk yt', 'shadow house mixes',
    'studio suno', 'sub pulse', 'suno hits', 'suno music', 'synthwavesz', 'techno b34tz',
    'techno black', 'techno is my life', 'techno king', 'techno-exe', 'this song is ai',
    'the ai music genre dictionary', 'ai mastery', 'traxtorm records', 'wave abyss records',
    'wildcore techno', 'zkxai - topic', 'zulvrendeepminimal'
]

FARM_TITLE_PATTERNS = [
    r'(?:202[4-9].*[🖤❤️⚫🐍🔥⚡💀🥀🎧✨⭐★].*(?:session|rave|mix|set|experience|descent|energy|horizons?)|[🖤❤️⚫🐍🔥⚡💀🥀🎧✨⭐★].*202[4-9].*(?:session|rave|mix|set|experience|descent|energy|horizons?))',
    r'\b(?:peak time .* session|deep hypnotic .* experience|hypnotic underground .* (?:mix|set)|industrial warehouse .* (?:session|mix|set)|dark forest rave|toxic euphoria|beyond the (?:dark )?horizon|the rave lives inside you|the dark never forgets|what the darkness left behind|the night pulls you in|when .* meets .*(?:\[no ads\]|\(no ads\))|\[no ads\].*(?:mix|set|session|hours)|underground female dj|female dj drops the beat|cyber rave energy|industrial warehouse techno)\b',
    r'\b(?:ai-generated tracks|generated by (?:suno|udio|ai)|made with (?:suno|udio)|suno ai showcase|suno studio|suno v[3-9]|udio v[1-9])\b',
    r'\b(?:techno mix 202[4-9]|techno bass mix 202[4-9]|phonk mix 202[4-9]|hardstyle rave mix 202[4-9])\s*[\uD800-\uDBFF][\uDC00-\uDFFF\s]*[A-Z0-9]'
]

FARM_CHANNEL_PATTERNS = [
    r'\b(?:session|sessions|echoes|dark tech|pulse beats|sound lab|mixes|cybermode|music lab|records|beats lab)\b'
]

CHATGPT_SNIPPET_PATTERNS = [
    r'(?:the dark has a memory longer than yours|the walls are silent, but the rhythm is loud|some journeys change you\. this one doesn\'t ask permission|you didn\'t choose to come here\. the night pulled you in|some raves were never meant to be found|this is not just a mix; it\'s a high-voltage descent|dive into a deep hypnotic journey|step into a hypnotic journey|travel beyond the (?:dark )?horizon|welcome to a deep, dark and hypnotic|nocturnal moon session delivers|lose yourself in the (?:dark )?rhythm|let the bass take over|feel the frequency\. heal your mind|crafted with advanced neural soundscapes)'
]

AI_CHANNEL_REGEX = r'(?:^|\s|#|@|\b)(?:ai|suno|udio|midjourney|generative|deepfake|synthetics?|aimusic|aivideo)(?:\b|\s|$)'

# Broad cross-genre search query collection
ALL_GENRES_QUERIES = [
    # Electronic, Techno & House
    'techno mix 2026', 'tech house mix 2025', 'dark techno', 'industrial techno', 'peak time techno',
    'minimal techno mix', 'acid techno rave', 'melodic techno 2025', 'deep house 2026', 'progressive house mix',
    'afro house 2025', 'slap house 2026', 'electro house mix', 'vocal trance mix', 'psytrance 2025',
    'hardstyle rave mix', 'rawstyle festival mix', 'drum and bass 2026', 'liquid dnb study', 'dubstep 2025',

    # Ambient, Lofi & Relaxation
    'ambient space music', 'lofi hip hop study', 'lofi beats to relax to', 'chillhop radio', 'dark ambient 10 hours',
    'sleep music 528hz', '432hz healing music', 'solfeggio frequencies 10 hours', 'deep sleep rain sounds',
    'meditation music 10 hours', 'relaxing piano mix', 'calm guitar instrumental', 'nature sounds 10 hours',

    # Hip Hop, Phonk & Trap
    'phonk mix 2025', 'drift phonk 2026', 'aggressive phonk', 'memphis phonk', 'trap metal mix',
    'hip hop boom bap mix', 'chill rap beats', 'hard trap beats 2025', 'instrumental hip hop', 'r&b soul mix 2026',

    # Rock, Heavy Metal & Punk
    'hard rock mix 2025', 'heavy metal gym mix', 'thrash metal 2026', 'death metal playlist', 'gothic rock mix',
    'post rock instrumental', 'shoegaze mix', 'pop punk nostalgia', 'indie rock playlist 2025', 'alternative rock 90s',

    # Pop, Dance & Commercial
    'top pop hits 2026', 'dance pop party mix', 'kpop playlist 2025', 'hyperpop mix', 'synthpop 80s style',
    'viral tiktok songs 2026', 'latin pop hits 2025', 'reggaeton mix 2026', 'afrobeats 2025',

    # Classical, Jazz & Blues
    'classical music for studying', 'mozart relax', 'beethoven piano sonatas', 'chopin nocturnes', 'baroque instrumental',
    'smooth jazz cafe', 'jazz hop chill', 'blues guitar instrumental', 'big band swing', 'gipsy jazz',

    # World, Folk & Country
    'country hits 2025', 'bluegrass instrumental', 'celtic folk music', 'nordic pagan folk', 'flamenco guitar',
    'bossa nova lounge', 'reggae dub mix', 'afrobeat chill', 'indian classical sitar', 'japanese koto relax',

    # Explicit AI Music & Voice Generator Queries
    'suno ai music', 'suno v3.5 songs', 'suno v4 bangers', 'udio ai song', 'udio v2 music',
    'ai cover song', 'rvc v2 voice clone', 'ai drake song', 'ai kanye west', 'ai voice clone cover',
    'ai singer song', 'ai country song', 'ai metal mix', 'ai rock song', 'ai pop music 2025',
    'ai beats prod by gpt', 'made with suno', 'generated by udio', 'ai lo-fi hip hop'
]

HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'Accept-Language': 'en-US,en;q=0.9'
}

def fetch_search_vids(query):
    url = f"https://www.youtube.com/results?search_query={quote_plus(query)}"
    req = Request(url, headers=HEADERS)
    try:
        with urlopen(req, timeout=8) as resp:
            html = resp.read().decode('utf-8', errors='ignore')
            vids = re.findall(r'"videoId":"([a-zA-Z0-9_-]{11})"', html)
            seen = set()
            res = []
            for v in vids:
                if v not in seen:
                    seen.add(v)
                    res.append(v)
            return res
    except Exception:
        return []

def evaluate_video(video_id):
    url = f"https://www.youtube.com/watch?v={video_id}"
    req = Request(url, headers=HEADERS)
    try:
        with urlopen(req, timeout=8) as resp:
            html = resp.read().decode('utf-8', errors='ignore')
    except Exception:
        return None

    data = parse_yt_data(html)
    title = data['title']
    channel = data['channel']
    desc = data['description']
    keywords_list = data['keywords']

    norm_title = normalize_text(title)
    norm_channel = normalize_text(channel)
    norm_desc = normalize_text(desc)
    c_lower = norm_channel.lower().strip()

    reasons = []

    if data['official_synthetic_label']:
        reasons.append("Official YouTube Disclosure")

    if any(cur in c_lower for cur in CURATED_CHANNELS):
        reasons.append("Curated AI Farm")

    if re.search(AI_CHANNEL_REGEX, c_lower, re.I):
        reasons.append("AI Channel Name")

    combined_text = f"{norm_title} {norm_desc} {' '.join(keywords_list)}".lower()
    matched_kws = set()
    for kw in KEYWORDS:
        escaped_kw = re.escape(kw)
        pattern = r'(?:#|\b)' + escaped_kw + r'\b'
        if re.search(pattern, combined_text, re.I):
            matched_kws.add(kw)

    if matched_kws:
        reasons.append(f"Keyword: {', '.join(sorted(list(matched_kws)))}")

    for pat in FARM_TITLE_PATTERNS:
        if re.search(pat, norm_title, re.I):
            reasons.append("Title Farm Formula")
            break

    for pat in FARM_CHANNEL_PATTERNS:
        if re.search(pat, norm_channel, re.I):
            reasons.append("Channel Naming Pattern")
            break

    for pat in CHATGPT_SNIPPET_PATTERNS:
        if re.search(pat, norm_desc, re.I):
            reasons.append("ChatGPT Description Formula")
            break

    is_ai = len(reasons) > 0
    return {
        'video_id': video_id,
        'title': title,
        'channel': channel,
        'is_ai': is_ai,
        'reasons': reasons
    }

def main():
    print(f"🌍 Starting Large-Scale Multi-Genre Search Harvest across {len(ALL_GENRES_QUERIES)} genres...")
    all_vids = []
    seen = set()

    with ThreadPoolExecutor(max_workers=20) as executor:
        futures = {executor.submit(fetch_search_vids, q): q for q in ALL_GENRES_QUERIES}
        for fut in as_completed(futures):
            q = futures[fut]
            vids = fut.result()
            added = 0
            for v in vids:
                if v not in seen:
                    seen.add(v)
                    all_vids.append(v)
                    added += 1
            print(f"  • Genre Query '{q}': +{added} vids (Total unique URLs: {len(all_vids)})")

    print(f"\n🚀 Running NoAI Inspection Engine on {len(all_vids)} unique YouTube URLs with 40 parallel workers...\n")
    
    start_time = time.time()
    results = []
    ai_count = 0
    ai_channels = set()
    reason_counts = {}

    with ThreadPoolExecutor(max_workers=40) as executor:
        futures = {executor.submit(evaluate_video, vid): vid for vid in all_vids}
        completed = 0
        for fut in as_completed(futures):
            completed += 1
            res = fut.result()
            if res:
                results.append(res)
                if res['is_ai']:
                    ai_count += 1
                    ai_channels.add(res['channel'])
                    for r in res['reasons']:
                        key = r.split(':')[0] if ':' in r else r
                        reason_counts[key] = reason_counts.get(key, 0) + 1
            
            if completed % 250 == 0 or completed == len(all_vids):
                pct = (ai_count / completed * 100) if completed > 0 else 0
                print(f"  [Progress] {completed}/{len(all_vids)} inspected... (AI Flagged: {ai_count} | {pct:.1f}%)")

    total_time = time.time() - start_time
    flag_pct = (ai_count / len(results) * 100) if results else 0

    report = {
        'total_scanned': len(results),
        'ai_flagged_count': ai_count,
        'ai_flagged_percent': round(flag_pct, 2),
        'execution_time_seconds': round(total_time, 2),
        'discovered_ai_channels_count': len(ai_channels),
        'discovered_ai_channels': sorted(list(ai_channels)),
        'reason_breakdown': reason_counts,
        'sample_ai_videos': [r for r in results if r['is_ai']][:30]
    }

    report_path = '/home/oh2fxd/toolbox/python/noai/batch_report_5000.json'
    with open(report_path, 'w', encoding='utf-8') as f:
        json.dump(report, f, indent=2, ensure_ascii=False)

    print("\n" + "="*70)
    print("🌍 LARGE-SCALE MULTI-GENRE YOUTUBE AI INSPECTION REPORT")
    print("="*70)
    print(f" Total Unique Videos Scanned : {len(results)}")
    print(f" Total AI Flagged            : {ai_count} ({flag_pct:.1f}%)")
    print(f" Real / Human Content        : {len(results) - ai_count} ({100 - flag_pct:.1f}%)")
    print(f" Discovered AI Channels      : {len(ai_channels)}")
    print(f" Execution Time             : {total_time:.2f} seconds ({len(results)/total_time:.1f} vids/sec)")
    print("-" * 70)
    print("🏆 BREAKDOWN OF MATCHED DETECTION REASONS:")
    for r, c in sorted(reason_counts.items(), key=lambda x: x[1], reverse=True):
        print(f"  • {r:<35}: {c} videos")
    print("="*70)
    print(f"\n📁 Saved full report to {report_path}")

if __name__ == '__main__':
    main()
