#!/usr/bin/env python3
"""
Fast High-Scale AI Marker Analysis via YouTube ytInitialData Search Extraction
Harvests thousands of rich video cards directly from YouTube search JSON without HTTP 429 rate limits.
Extracts detailed markers for all detected AI videos:
- Emojis used in titles & descriptions
- Hashtags
- ChatGPT bio/description text patterns
- Title formulas & clickbait markers
- Channel naming styles
- Disclosure sources
"""

import re
import json
import os
import sys
import time
from urllib.request import Request, urlopen
from urllib.parse import quote_plus
from concurrent.futures import ThreadPoolExecutor, as_completed

# 50 Target Genres across Electronic, Ambient, Phonk, Lofi, AI Music, Rock, Jazz, Classical, World, etc.
GENRES = [
    # Electronic & Dance
    "Dark Techno", "Industrial Techno", "Peak Time Techno", "Minimal Techno", "Acid Techno",
    "Melodic Techno", "Deep House", "Tech House", "Progressive House", "Afro House",
    "Trance", "Psytrance", "Hardstyle", "Drum and Bass", "Dubstep", "Synthwave", "Cyberpunk",

    # Ambient, Chill & Relaxation
    "Dark Ambient", "Lofi Hip Hop", "Relaxing Piano", "Meditation 528Hz", "Nature Sounds",
    "Binaural Beats", "ASMR", "Space Ambient", "Solfeggio Frequencies", "Chillhop",

    # Hip Hop, Phonk & Trap
    "Drift Phonk", "Memphis Phonk", "Aggressive Phonk Gym", "Trap Metal", "Modern Trap",
    "Cloud Rap", "Underground Rap", "Instrumental Hip Hop", "R&B Soul",

    # Rock & Heavy Metal
    "Heavy Metal", "Thrash Metal", "Gothic Rock", "Post Rock", "Shoegaze",
    "Pop Punk", "Indie Rock", "Progressive Metal", "Alternative Rock",

    # Classical, Jazz & World
    "Classical Piano", "Smooth Jazz", "Bossa Nova", "Nordic Folk", "Celtic Folk",

    # Synthetic Media & AI
    "Suno AI Music", "Udio AI Songs", "AI Cover Songs", "AI Voice Clones"
]

KEYWORDS = [
    'suno', 'suno.ai', 'suno ai', 'suno v3', 'suno v3.5', 'suno v4', 'suno v5', 'suno v6', 'suno studio',
    'udio', 'udio.ai', 'udio ai', 'udio v1', 'udio v1.5', 'udio v2',
    'elevenlabs', 'eleven labs', '11labs', 'fakeyou', 'uberduck', 'tortoise tts', 'rvc', 'rvc v2',
    'so-vits-svc', 'sovits', 'bark ai', 'voice clone', 'voice cloning', 'ai voice', 'ai vocals',
    'ai singer', 'ai cover', 'ai covers', 'ai duet', 'ai song', 'ai songs', 'ai rap', 'ai beat', 'ai beats',
    'ai track', 'ai tracks', 'ai audio', 'ai generated music', 'ai generated song', 'prompted music', 'riffusion', 'musicgen',
    'ai drake', 'ai kanye', 'ai trump', 'ai biden', 'ai obama', 'ai spongebob', 'ai plankton',
    'ai michael jackson', 'ai freddie mercury', 'ai the weeknd', 'ai eminem', 'ai taylor swift',
    'sora 2', 'sora openai', 'sora ai', 'runwayml', 'gen-2', 'gen-3', 'gen-3 alpha', 'gen3 alpha',
    'kling ai', 'kling 1.5', 'pika labs', 'pika 1.0', 'pika 2.0', 'luma ai', 'luma dream machine',
    'minimax video', 'minimax ai', 'hailuo ai', 'hailuo 01', 'haiper ai', 'viggle ai', 'google veo', 'veo google',
    'ltx video', 'cogvideo', 'mochi 1', 'wan 2.1', 'wan2.1', 'hunyuan video', 'animatediff',
    'deforum stable diffusion', 'infinite zoom ai',
    'ai animation', 'ai animated video', 'ai film', 'ai movie', 'ai cinema', 'ai trailer', 'ai visualizer',
    'midjourney v5', 'midjourney v6', 'midjourney v7', 'dall-e 3', 'dalle3',
    'stable diffusion', 'sdxl', 'sd1.5', 'sd3', 'flux.1', 'flux dev', 'flux schnell', 'recraft',
    'comfyui', 'leonardo ai', 'ideogram ai', 'magnific ai',
    'ai art generator', 'ai artwork generator', 'ai illustration generator',
    'generative ai music', 'ai generated video', 'ai generated track',
    'generated with ai', 'generated by ai', 'made with ai', 'created with ai', 'created using ai',
    'powered by ai', 'synthesized with ai', 'synthetic media', 'synthetic voice',
    'ai model prompt', 'prompts shared',
    'suno.com', 'udio.com', 'elevenlabs.io', 'midjourney.com', 'replicate.com/spaces',
    'ki generiert', 'generado por ia', 'hecho con ia', 'généré par ia', 'создано ии', 'нейросеть',
    'ai生成', '画像生成ai', '音楽生成ai'
]

CURATED_AI_CHANNELS = [
    'amoda session', 'astral phonk', 'atus music', 'berlin pulse', 'brahman games',
    'chili ai music', 'chill music lab', 'cinecipher', 'cybermode beats', 'cyberfalco',
    'cyber cyber', 'cyprus rave', 'dark noir techno', 'deep flow techno', 'digital pulse beats',
    'dolopz', 'dreamy darlings', 'echoloop', 'far east echoes', 'fristok', 'goth dark techno',
    'grand sound', 'grandsound', 'hard wind frequencies', 'helio432hz', 'human music',
    'hypertechfury', 'hypnotic night sessions', 'krya dark tech', 'larub techno sessions',
    'magic techno', 'melodic techno space', 'midnight sessions', 'misstiq', 'moebius fm',
    'muzlub', 'neutral phonks', 'nocturnal moon session', 'nocturne echoes',
    'nocturne echoes and nocturne cello', 'obsidian hyper techno',
    'occultus records & black square recordings', 'phonk yt', 'shadow house mixes',
    'studio suno', 'sub pulse', 'suno hits', 'suno music', 'synthwavesz', 'techno b34tz',
    'techno black', 'techno is my life', 'techno king', 'techno-exe', 'this song is ai',
    'the ai music genre dictionary', 'ai mastery', 'traxtorm records', 'wave abyss records',
    'wildcore techno', 'zkxai - topic', 'zulvrendeepminimal'
]

AI_CHANNEL_REGEX = re.compile(
    r'(?:^|\s|#|@|\b)(?:suno\s*ai|udio\s*ai|ai\s*covers?|ai\s*music|ai\s*tracks?|ai\s*beats?|ai\s*generated|generative\s*ai\s*music|aimusic)(?:\b|\s|$)',
    re.I
)

FARM_TITLE_PATTERNS = [
    re.compile(r'(?:[🖤❤️⚫🐍🔥⚡💀🥀🎧✨⭐★]{2,}.*(?:session|rave|mix|set|experience|descent|energy|horizons?))', re.I),
    re.compile(r'\b(?:peak time .* session|deep hypnotic .* experience|hypnotic underground .* (?:mix|set)|industrial warehouse .* (?:session|mix|set)|dark forest rave|toxic euphoria|beyond the (?:dark )?horizon|the rave lives inside you|the dark never forgets|what the darkness left behind|the night pulls you in|underground female dj|female dj drops the beat|cyber rave energy)\b', re.I),
    re.compile(r'\b(?:ai-generated tracks|generated by (?:suno|udio)|made with (?:suno|udio)|suno ai showcase|suno studio|suno v[3-9]|udio v[1-9])\b', re.I)
]

FARM_CHANNEL_PATTERNS = [
    re.compile(r'\b(?:dark tech|cybermode|beats lab|techno-exe)\b', re.I),
    re.compile(r'\b(?:dark techno|deep techno|phonk|lofi|ai music|suno|udio)\s*-\s*topic\b', re.I)
]

CHATGPT_SNIPPET_PATTERNS = [
    re.compile(r'(?:the dark has a memory longer than yours|the walls are silent, but the rhythm is loud|some journeys change you\. this one doesn\'t ask permission|you didn\'t choose to come here\. the night pulled you in|some raves were never meant to be found|this is not just a mix; it\'s a high-voltage descent|dive into a deep hypnotic journey|step into a hypnotic journey|travel beyond the (?:dark )?horizon|welcome to a deep, dark and hypnotic|nocturnal moon session delivers|lose yourself in the (?:dark )?rhythm|let the bass take over|feel the frequency\. heal your mind|crafted with advanced neural soundscapes)', re.I)
]

EMOJI_REGEX = re.compile(r'[\U0001F300-\U0001F9FF\u2600-\u26FF\u2700-\u27BF🖤❤️⚫🐍🔥⚡💀🥀🎧✨⭐★]')

def compile_keyword_regex():
    escaped = []
    for k in KEYWORDS:
        k = k.strip()
        if not k: continue
        bare = k[1:] if k.startswith('#') else k
        esc = re.escape(bare)
        escaped.append(rf'(?:#|\b){esc}\b')
    pattern = '|'.join(escaped)
    return re.compile(rf'({pattern})', re.I)

keyword_regex = compile_keyword_regex()

def harvest_and_parse_genre(genre):
    encoded = quote_plus(f"{genre} mix")
    url = f"https://www.youtube.com/results?search_query={encoded}"
    req = Request(url, headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0 Safari/537.36', 'Accept-Language': 'en-US,en;q=0.9'})
    cards = []
    try:
        with urlopen(req, timeout=12) as resp:
            html = resp.read().decode('utf-8', errors='ignore')
            m = re.search(r'var ytInitialData = (\{.*?\});</script>', html)
            if m:
                data = json.loads(m.group(1))
                contents = data.get('contents', {}).get('twoColumnSearchResultsRenderer', {}).get('primaryContents', {}).get('sectionListRenderer', {}).get('contents', [])
                for sec in contents:
                    items = sec.get('itemSectionRenderer', {}).get('contents', [])
                    for item in items:
                        v = item.get('videoRenderer')
                        if v:
                            v_id = v.get('videoId', '')
                            title = v.get('title', {}).get('runs', [{}])[0].get('text', '')
                            channel = v.get('ownerText', {}).get('runs', [{}])[0].get('text', '')
                            desc_snippets = v.get('detailedMetadataSnippets', [{}])[0].get('snippetText', {}).get('runs', [])
                            desc = ''.join([r.get('text', '') for r in desc_snippets])
                            badges = [b.get('metadataBadgeRenderer', {}).get('label', '') for b in v.get('badges', [])]
                            
                            is_official_ai = any(w in ' '.join(badges).lower() or w in html.lower() for w in ['synthetic', 'altered', 'made with ai', 'ai-generated'])
                            cards.append({
                                "id": v_id,
                                "genre": genre,
                                "title": title,
                                "channel": channel,
                                "desc": desc,
                                "badges": badges,
                                "official_ai": is_official_ai
                            })
    except Exception as e:
        print(f"  ❌ Error harvesting {genre}: {e}")
    return genre, cards

def check_card(title, channel, desc='', official_label=False):
    channel_lower = channel.lower()
    for known in CURATED_AI_CHANNELS:
        if known in channel_lower:
            return True, 'Curated AI Farm'
    if AI_CHANNEL_REGEX.search(channel):
        return True, 'AI Channel'
    if official_label:
        return True, 'YouTube AI Disclosure'
    combined = f"{title} {desc}"
    m = keyword_regex.search(combined)
    if m:
        found = m.group(1) or m.group(0)
        return True, f"Keyword: {found.strip().upper()}"
    score = 0
    for tp in FARM_TITLE_PATTERNS:
        if tp.search(title):
            score += 30; break
    for cp in FARM_CHANNEL_PATTERNS:
        if cp.search(channel):
            score += 25; break
    if desc:
        for sp in CHATGPT_SNIPPET_PATTERNS:
            if sp.search(desc):
                score += 40; break
    if score >= 50:
        return True, f'AI Farm Heuristic (score={score})'
    return False, 'Legitimate'

def main():
    start_time = time.time()
    print("🚀 Starting Fast High-Scale AI Marker Analysis...")
    
    # Harvest all genres in parallel
    genre_cards_map = {}
    print(f"\n--- STEP 1: Harvesting & Extracting Metadata across {len(GENRES)} Genres ---")
    with ThreadPoolExecutor(max_workers=15) as executor:
        futures = [executor.submit(harvest_and_parse_genre, g) for g in GENRES]
        for f in as_completed(futures):
            g, cards = f.result()
            genre_cards_map[g] = cards
            print(f"  • {g:30s}: Extracted {len(cards)} rich video cards")
            
    all_cards = []
    for g, cards in genre_cards_map.items():
        all_cards.extend(cards)
        
    print(f"\nTotal Rich Video Cards Collected: {len(all_cards)}")
    
    # STEP 2: Evaluate Detections and Extract Detailed Markers
    print("\n--- STEP 2: Evaluating Detections & Extracting Markers ---")
    ai_flagged = []
    genre_stats = {g: {"total": 0, "ai_count": 0, "ai_pct": 0.0} for g in GENRES}
    
    for card in all_cards:
        g = card["genre"]
        genre_stats[g]["total"] += 1
        
        is_ai, reason = check_card(card["title"], card["channel"], desc=card["desc"], official_label=card["official_ai"])
        if is_ai:
            ai_flagged.append({
                "id": card["id"],
                "genre": g,
                "title": card["title"],
                "channel": card["channel"],
                "reason": reason,
                "markers": {
                    "emojis": list(set(EMOJI_REGEX.findall(f"{card['title']} {card['desc']}"))),
                    "hashtags": list(set(re.findall(r'#\w+', f"{card['title']} {card['desc']}"))),
                    "writing_patterns": [sp.search(card['desc']).group(0) for sp in CHATGPT_SNIPPET_PATTERNS if sp.search(card['desc'])],
                    "title_features": ([ "[No Ads] Clickbait" ] if re.search(r'\[no ads\]|\(no ads\)', card['title'], re.I) else []) +
                                     ([ "Year Tag" ] if re.search(r'202[4-9]', card['title']) else []),
                    "channel_style": ([ "Content Farm Naming" ] if re.search(r'\b(?:session|sessions|records|music lab|beats|pulse)\b', card['channel'], re.I) else [])
                }
            })
            genre_stats[g]["ai_count"] += 1

    for g in GENRES:
        t = genre_stats[g]["total"]
        a = genre_stats[g]["ai_count"]
        genre_stats[g]["ai_pct"] = round((a / t * 100), 2) if t > 0 else 0.0

    # Step 3: Aggregate Marker Frequency Statistics
    emoji_freq = {}
    hashtag_freq = {}
    writing_freq = {}
    title_feature_freq = {}
    channel_style_freq = {}
    reason_freq = {}

    for item in ai_flagged:
        m = item["markers"]
        for e in m["emojis"]:
            emoji_freq[e] = emoji_freq.get(e, 0) + 1
        for h in m["hashtags"]:
            hashtag_freq[h] = hashtag_freq.get(h, 0) + 1
        for w in m["writing_patterns"]:
            writing_freq[w] = writing_freq.get(w, 0) + 1
        for tf in m["title_features"]:
            title_feature_freq[tf] = title_feature_freq.get(tf, 0) + 1
        for cs in m["channel_style"]:
            channel_style_freq[cs] = channel_style_freq.get(cs, 0) + 1
        reason_freq[item["reason"]] = reason_freq.get(item["reason"], 0) + 1

    elapsed = round(time.time() - start_time, 2)

    report = {
        "total_genres": len(GENRES),
        "total_videos_evaluated": len(all_cards),
        "total_ai_flagged": len(ai_flagged),
        "overall_ai_pct": round((len(ai_flagged) / len(all_cards) * 100), 2) if all_cards else 0.0,
        "elapsed_seconds": elapsed,
        "genre_stats": genre_stats,
        "marker_aggregates": {
            "top_emojis": sorted(emoji_freq.items(), key=lambda x: x[1], reverse=True),
            "top_hashtags": sorted(hashtag_freq.items(), key=lambda x: x[1], reverse=True),
            "writing_patterns": sorted(writing_freq.items(), key=lambda x: x[1], reverse=True),
            "title_features": sorted(title_feature_freq.items(), key=lambda x: x[1], reverse=True),
            "channel_styles": sorted(channel_style_freq.items(), key=lambda x: x[1], reverse=True),
            "detection_sources": sorted(reason_freq.items(), key=lambda x: x[1], reverse=True)
        },
        "flagged_sample_details": ai_flagged
    }

    out_file = "/home/oh2fxd/toolbox/python/noai/deep_marker_report_final.json"
    with open(out_file, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)

    print(f"\n==================================================")
    print(f"ANALYSIS COMPLETE in {elapsed}s!")
    print(f"Total Evaluated: {len(all_cards)}")
    print(f"Total AI Flagged: {len(ai_flagged)} ({report['overall_ai_pct']}%)")
    print(f"Report saved to: {out_file}")

if __name__ == "__main__":
    main()
