#!/usr/bin/env python3
"""
YouTube AI Content Inspector Tool
Analyzes a YouTube video URL to inspect its title, description, channel, and metadata
for AI-generated content signals, YouTube native synthetic media disclosures,
and automated content-farm patterns.
"""

import sys
import os
import re
import json
import argparse
from urllib.request import Request, urlopen
from urllib.parse import urlparse, parse_qs

# Keywords from NoAI content.js
KEYWORDS = [
    'ai', 'suno', 'suno.ai', 'suno ai', 'suno v3', 'suno v4', 'suno v5', 'suno v6', 'suno studio',
    'udio', 'udio.ai', 'udio ai', 'udio v1', 'udio v1.5', 'udio v2',
    'elevenlabs', 'eleven labs', '11labs', 'fakeyou', 'uberduck', 'tortoise tts', 'rvc', 'rvc v2',
    'so-vits-svc', 'sovits', 'bark ai', 'voice clone', 'voice cloning', 'ai voice', 'ai vocals',
    'ai singer', 'ai cover', 'ai covers', 'ai duet', 'ai song', 'ai songs', 'ai rap', 'ai beat', 'ai beats',
    'ai track', 'ai tracks', 'ai audio', 'ai generated music', 'prompted music', 'riffusion', 'musicgen',
    'ai drake', 'ai kanye', 'ai trump', 'ai biden', 'ai obama', 'ai spongebob', 'ai plankton',
    'ai michael jackson', 'ai freddie mercury', 'ai the weeknd', 'ai eminem', 'ai taylor swift',
    'sora', 'sora 2', 'sora openai', 'runway', 'runwayml', 'gen-2', 'gen-3', 'gen-3 alpha', 'gen3 alpha',
    'kling', 'kling ai', 'kling 1.5', 'pika', 'pika labs', 'pika 1.0', 'pika 2.0', 'luma', 'luma ai',
    'dream machine', 'minimax', 'minimax video', 'hailuo', 'hailuo ai', 'haiper', 'haiper ai',
    'viggle', 'viggle ai', 'veo', 'google veo', 'ltx video', 'cogvideo', 'mochi 1', 'animatediff',
    'deforum', 'deforum stable diffusion', 'infinite zoom ai',
    'ai animation', 'ai animated', 'ai video', 'ai film', 'ai movie', 'ai cinema', 'ai trailer', 'ai visualizer',
    'midjourney', 'midjourney v5', 'midjourney v6', 'midjourney v7', 'dall-e', 'dall-e 3', 'dalle', 'dalle3',
    'stable diffusion', 'sdxl', 'sd1.5', 'sd3', 'flux.1', 'flux', 'flux dev', 'flux schnell',
    'comfyui', 'leonardo ai', 'ideogram', 'ideogram ai', 'magnific', 'magnific ai',
    'ai art', 'ai artwork', 'ai illustration',
    'generative ai', 'gen ai', 'genai', 'ai generated', 'generated with ai', 'generated by ai',
    'made with ai', 'created with ai', 'created using ai', 'powered by ai', 'synthesized with ai',
    'deepfake', 'deep fake', 'synthetic media', 'synthetic voice', 'chatgpt', 'chat gpt', 'gpt-4', 'gpt-4o',
    'ai model', 'ai prompts', 'prompt sharing', 'prompt:', 'prompts shared',
    'ki generiert', 'generado por ia', 'hecho con ia', 'généré par ia', 'создано ии', 'нейросеть',
    'ai生成', '画像生成ai', '音楽生成ai'
]

CURATED_CHANNELS = [
    'techno b34tz',
    'synthwavesz',
    'phonk yt',
    'neutral phonks',
    'moebius fm',
    'melodic techno space',
    'deep flow techno',
    'cyprus rave',
    'chill music lab',
    'cinecipher',
    'berlin pulse',
    'atus music',
    'astral phonk',
    'dolopz',
    'zulvrendeepminimal',
    'wave abyss records',
    'techno-exe',
    'techno king',
    'sub pulse',
    'midnight sessions',
    'magic techno',
    'larub techno sessions',
    'hypertechfury',
    'hard wind frequencies',
    'goth dark techno',
    'far east echoes',
    'echoloop',
    'cybermode beats',
    'cyberfalco',
    'chili ai music',
    'muzlub', 'grandsound', 'grand sound', 'krya dark tech', 'amoda session',
    'techno black', 'nocturnal moon session', 'hypnotic night sessions',
    'nocturne echoes', 'dark noir techno', 'wildcore techno', 'shadow house mixes',
    'digital pulse beats', 'obsidian hyper techno', 'techno is my life',
    'cyber cyber', 'dreamy darlings', 'neurotune', 'this song is ai',
    'the ai music genre dictionary', 'ai mastery', 'helio432hz', 'studio suno',
    'suno hits', 'suno music'
]

FARM_TITLE_PATTERNS = [
    r'(?:202[4-9].*[🖤❤️⚫🐍🔥⚡💀🥀🎧✨⭐★].*(?:session|rave|mix|set|experience|descent|energy|horizons?)|[🖤❤️⚫🐍🔥⚡💀🥀🎧✨⭐★].*202[4-9].*(?:session|rave|mix|set|experience|descent|energy|horizons?))',
    r'\b(?:peak time .* session|deep hypnotic .* experience|hypnotic underground .* (?:tech house|techno|house|rave|mix|set|experience|groove)|dark club bass|deep groove in .* forest|industrial warehouse .* (?:session|mix|set)|dark forest rave|toxic euphoria|beyond the (?:dark )?horizon|the rave lives inside you|the dark never forgets|what the darkness left behind|the night pulls you in|when .* meets .*(?:\[no ads\]|\(no ads\))|\[no ads\].*(?:mix|set|session|hours)|underground female dj|female dj drops the beat|cyber rave energy|industrial warehouse techno)\b',
    r'\b(?:ai-generated tracks|generated by (?:suno|udio|ai)|made with (?:suno|udio)|suno ai showcase|suno studio|suno v[3-9]|udio v[1-9])\b',
    r'\b(?:tech house|techno|deep house|trance|cyberpunk|synthwave)\s+202[4-9]\s*\|\s*[^|]+\|\s*[^|\n]+\b'
]

FARM_CHANNEL_PATTERNS = [
    r'\b(?:session|sessions|echoes|dark tech|pulse|pulse beats|sound lab|mixes|cybermode|music lab|records|beats lab)\b'
]

CHATGPT_SNIPPET_PATTERNS = [
    r'(?:the dark has a memory longer than yours|the walls are silent, but the rhythm is loud|some journeys change you\. this one doesn\'t ask permission|you didn\'t choose to come here\. the night pulled you in|some raves were never meant to be found|this is not just a mix; it\'s a high-voltage descent|dive into a deep hypnotic journey|step into a hypnotic journey|travel beyond the (?:dark )?horizon|welcome to a deep, dark and hypnotic|nocturnal moon session delivers|lose yourself in the (?:dark )?rhythm|let the bass take over|step into the dark forest|feel the atmosphere\. hear the bass|get lost in the groove|perfect for:.*late night drives|deep basslines, hypnotic rhythms|this mix creates a dark and cinematic vibe|warning: this mix may cause deep immersion|stay underground\. stay dark|expected deep bass|smooth and immersive, pulling you deeper|perfect for:.*(?:gym|drives|gaming|focus))'
]

CONTENT_ID_AI_MUSIC_REGEX = r'\b(?:provided to youtube by|auto-generated by youtube)\b[\s\S]*?\b(?:suno|udio|distrokid ai|amuse ai|landr ai)\b'
SHORTS_AUTOMATION_REGEX = r'\b(?:what happens if|3 facts about|did you know that|unbelievable facts)\b.*#(?:shorts|ai|elevenlabs|aivoice|gpt4|voiceover)\b'
EMOJI_FARM_REGEX = r'(?:[🖤❤️⚫🐍🔥⚡💀🥀🎧✨⭐★][\s]*){3,}'
DISPOSABLE_HANDLE_REGEX = r'^@user-[a-z0-9]{8,12}$'

AI_CHANNEL_REGEX = r'(?:^|\s|#|@|\b)(?:ai|suno|udio|midjourney|generative|deepfake|synthetics?|aimusic|aivideo)(?:\b|\s|$)'

import unicodedata

def normalize_text(text):
    if not text:
        return ""
    return unicodedata.normalize('NFKD', text)

def extract_video_id(url):
    """Extract 11-char YouTube video ID from various URL formats."""
    parsed = urlparse(url)
    if parsed.netloc in ('youtu.be', 'www.youtu.be'):
        return parsed.path.lstrip('/')
    if 'youtube.com' in parsed.netloc or 'youtube-nocookie.com' in parsed.netloc:
        if parsed.path == '/watch':
            return parse_qs(parsed.query).get('v', [None])[0]
        elif parsed.path.startswith('/shorts/'):
            return parsed.path.split('/shorts/')[1].split('?')[0]
        elif parsed.path.startswith('/v/'):
            return parsed.path.split('/v/')[1].split('?')[0]
    # If standard 11-char string passed directly
    if re.match(r'^[a-zA-Z0-9_-]{11}$', url):
        return url
    return None

def fetch_youtube_page(video_id):
    """Fetch raw YouTube video page HTML."""
    url = f'https://www.youtube.com/watch?v={video_id}'
    req = Request(
        url,
        headers={
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            'Accept-Language': 'en-US,en;q=0.9'
        }
    )
    try:
        with urlopen(req, timeout=15) as resp:
            return resp.read().decode('utf-8', errors='ignore')
    except Exception as e:
        print(f"❌ Error fetching YouTube URL ({url}): {e}")
        return None

def parse_yt_data(html):
    """Extract metadata, player response, and initial data from raw HTML."""
    data = {
        'title': '',
        'channel': '',
        'description': '',
        'keywords': [],
        'official_synthetic_label': False,
        'synthetic_details': [],
        'raw_json': {}
    }

    # Extract Title via og:title or ytInitialPlayerResponse
    title_match = re.search(r'<meta property="og:title" content="([^"]+)"', html)
    if title_match:
        data['title'] = title_match.group(1)

    # Extract Channel via og:video:tag or ownerChannelName
    channel_match = re.search(r'<link itemprop="name" content="([^"]+)"', html) or re.search(r'"author":"([^"]+)"', html)
    if channel_match:
        data['channel'] = channel_match.group(1)

    # Extract Description via meta description or JSON
    desc_match = re.search(r'<meta property="og:description" content="([^"]+)"', html) or re.search(r'<meta name="description" content="([^"]+)"', html)
    if desc_match:
        data['description'] = desc_match.group(1)

    # Look for ytInitialPlayerResponse
    pr_match = re.search(r'var ytInitialPlayerResponse\s*=\s*({.+?});</script>', html)
    if pr_match:
        try:
            player_data = json.loads(pr_match.group(1))
            video_details = player_data.get('videoDetails', {})
            if video_details.get('title'):
                data['title'] = video_details.get('title')
            if video_details.get('author'):
                data['channel'] = video_details.get('author')
            if video_details.get('shortDescription'):
                data['description'] = video_details.get('shortDescription')
            if video_details.get('keywords'):
                data['keywords'] = video_details.get('keywords')
        except Exception:
            pass

    # Check for Native YouTube Synthetic Disclosures
    if re.search(r'"isSyntheticMedia":true|"alteredOrSyntheticContent":true|"syntheticMedia":true', html, re.I):
        data['official_synthetic_label'] = True
        data['synthetic_details'].append("Native YouTube 'Altered or synthetic content' flag present in page JSON.")

    if 'sound or visual content that was significantly altered or generated' in html.lower() or 'altered or synthetic content' in html.lower():
        data['official_synthetic_label'] = True
        data['synthetic_details'].append("Native YouTube disclosure text detected in HTML.")

    return data

def inspect_video(video_input):
    video_id = extract_video_id(video_input)
    if not video_id:
        print(f"❌ Invalid YouTube URL or Video ID: {video_input}")
        return

    print(f"\n🔍 Fetching YouTube metadata for ID: {video_id}...")
    html = fetch_youtube_page(video_id)
    if not html:
        return

    data = parse_yt_data(html)

    title = data['title']
    channel = data['channel']
    desc = data['description']
    keywords_list = data['keywords']

    print("=" * 70)
    print(f"🎬 TITLE    : {title}")
    print(f"👤 CHANNEL  : {channel}")
    print(f"📝 DESC     : {desc[:200]}{'...' if len(desc) > 200 else ''}")
    if keywords_list:
        print(f"🏷️ TAGS     : {', '.join(keywords_list[:10])}")
    print("=" * 70)

    reasons = []

    # 1. Official Disclosure Check
    if data['official_synthetic_label']:
        reasons.append("OFFICIAL_LABEL: YouTube native 'Altered or Synthetic Content' disclosure detected.")
        for d in data['synthetic_details']:
            reasons.append(f"   └─ {d}")

    # 2. Curated Channel Check
    c_lower = channel.lower().strip()
    if any(cur in c_lower for cur in CURATED_CHANNELS):
        reasons.append(f"CURATED_CHANNEL: Channel '{channel}' is in the known AI content-farm list.")

    # 3. Channel Name Pattern Check
    if re.search(AI_CHANNEL_REGEX, channel, re.I):
        reasons.append(f"CHANNEL_NAME: Channel name '{channel}' contains explicit AI keywords.")
    
    for pat in FARM_CHANNEL_PATTERNS:
        if re.search(pat, channel, re.I):
            reasons.append(f"FARM_CHANNEL_PATTERN: Channel '{channel}' matches automated content-farm naming formula.")

    # 4. Keyword Detection (Title, Description, Tags)
    text_to_scan = f"{title} {desc} {' '.join(keywords_list)}".lower()

    matched_keywords = set()
    for kw in KEYWORDS:
        # Regex boundary check
        escaped_kw = re.escape(kw)
        pattern = r'(?:#|\b)' + escaped_kw + r'\b'
        if re.search(pattern, text_to_scan, re.I):
            matched_keywords.add(kw)

    if matched_keywords:
        reasons.append(f"KEYWORDS: Matched AI tool/gen keywords: {sorted(list(matched_keywords))}")

    # 5. Content-Farm Title Formulas
    for pat in FARM_TITLE_PATTERNS:
        if re.search(pat, title, re.I):
            reasons.append(f"FARM_TITLE_PATTERN: Title matches automated clickbait formula pattern.")
            break

    # 6. ChatGPT Description Formulas
    for pat in CHATGPT_SNIPPET_PATTERNS:
        m = re.search(pat, desc, re.I)
        if m:
            reasons.append(f"CHATGPT_DESCRIPTION: Description matches synthetic formula ('{m.group(0)}').")
            break

    # EVALUATION
    is_ai = len(reasons) > 0

    print("\n📊 INSPECTION RESULTS:")
    if is_ai:
        print("🚨 FLAG STATUS : [ AI GENERATED CONTENT DETECTED ]")
        print("\nREASONS MATCHED:")
        for r in reasons:
            print(f"  • {r}")
    else:
        print("✅ FLAG STATUS : [ NOT CURRENTLY FLAGGED AS AI ]")
        print("\n💡 If this video is AI-generated, you can add its new channel name or keywords to content.js!")
        print("   Suggested command: python3 inspect_youtube_ai.py --add-keyword <new_keyword>")

    print("=" * 70 + "\n")

def main():
    parser = argparse.ArgumentParser(description="Inspect YouTube URL for AI content signals.")
    parser.add_argument("url", nargs="?", help="YouTube video URL or Video ID")
    parser.add_argument("--add-keyword", help="Add a new keyword to content.js")
    parser.add_argument("--add-channel", help="Add a new channel name to content.js")

    args = parser.parse_args()

    content_js_path = "/home/oh2fxd/toolbox/python/noai/youtube-noai/content/content.js"

    if args.add_keyword:
        kw = args.add_keyword.strip().lower()
        if not os.path.exists(content_js_path):
            print(f"❌ Could not find {content_js_path}")
            return
        with open(content_js_path, "r", encoding="utf-8") as f:
            content = f.read()
        if f"'{kw}'" in content:
            print(f"⚠️ Keyword '{kw}' is already in content.js!")
        else:
            # Add to customKeywords array
            updated = content.replace("customKeywords: [", f"customKeywords: [\n      '{kw}',")
            with open(content_js_path, "w", encoding="utf-8") as f:
                f.write(updated)
            print(f"✅ Added keyword '{kw}' to content.js!")
        return

    if args.add_channel:
        chan = args.add_channel.strip().lower()
        if not os.path.exists(content_js_path):
            print(f"❌ Could not find {content_js_path}")
            return
        with open(content_js_path, "r", encoding="utf-8") as f:
            content = f.read()
        if f"'{chan}'" in content:
            print(f"⚠️ Channel '{chan}' is already in content.js CURATED_AI_CHANNELS!")
        else:
            updated = content.replace("const CURATED_AI_CHANNELS = [", f"const CURATED_AI_CHANNELS = [\n    '{chan}',")
            with open(content_js_path, "w", encoding="utf-8") as f:
                f.write(updated)
            print(f"✅ Added channel '{chan}' to content.js CURATED_AI_CHANNELS!")
        return

    if not args.url:
        parser.print_help()
        sys.exit(1)

    inspect_video(args.url)

if __name__ == "__main__":
    main()
