// NoAI YouTube Content Script

(() => {
  'use strict';

  // Inline SVG assets to bypass any YouTube Content-Security-Policy (CSP) img-src blocks
  const AI_BADGE_SVG = `
    <svg class="noai-badge-svg" viewBox="0 0 148 42" width="148" height="42" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <linearGradient id="noaiGrad" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stop-color="#e11d48"/>
          <stop offset="60%" stop-color="#be123c"/>
          <stop offset="100%" stop-color="#881337"/>
        </linearGradient>
        <filter id="noaiShadow" x="-10%" y="-10%" width="130%" height="130%">
          <feDropShadow dx="0" dy="2" stdDeviation="2.5" flood-color="#000" flood-opacity="0.8"/>
        </filter>
      </defs>
      <rect x="2" y="2" width="144" height="38" rx="8" fill="url(#noaiGrad)" stroke="#ffffff" stroke-width="1.5" filter="url(#noaiShadow)"/>
      <path d="M18 9 L21 17 L29 19 L21 21 L18 29 L15 21 L7 19 L15 17 Z" fill="#ffffff"/>
      <circle cx="18" cy="19" r="2" fill="#f43f5e"/>
      <text x="36" y="23" font-family="-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif" font-size="12" font-weight="900" fill="#ffffff" letter-spacing="0.6">AI GENERATED</text>
      <text x="36" y="33" font-family="-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif" font-size="8.5" font-weight="700" fill="#fecdd3" letter-spacing="0.4">SYNTHETIC MEDIA</text>
    </svg>
  `;

  const NO_AI_BLOCK_SVG = `
    <svg class="noai-block-svg" viewBox="0 0 96 36" width="96" height="36" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <filter id="noaiBlockShadow" x="-10%" y="-10%" width="130%" height="130%">
          <feDropShadow dx="0" dy="2" stdDeviation="2" flood-color="#000" flood-opacity="0.8"/>
        </filter>
      </defs>
      <rect x="2" y="2" width="92" height="32" rx="7" fill="#0f172a" stroke="#e11d48" stroke-width="1.8" filter="url(#noaiBlockShadow)"/>
      <circle cx="18" cy="18" r="9.5" fill="none" stroke="#e11d48" stroke-width="2.4"/>
      <line x1="11" y1="25" x2="25" y2="11" stroke="#e11d48" stroke-width="2.4"/>
      <text x="13" y="21" font-family="-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif" font-size="7.5" font-weight="900" fill="#ffffff">AI</text>
      <text x="36" y="22" font-family="-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif" font-size="11" font-weight="800" fill="#fda4af" letter-spacing="0.5">BLOCK</text>
    </svg>
  `;

  let config = {
    enabled: true,
    action: 'tag', // default to 'tag' with big picture badge
    detectOfficialLabels: true,
    detectKeywords: true,
    detectChannelList: true,
    enableCuratedList: true,
    detectContentFarmPatterns: true,
    enableQuickBlockButton: true,
    customKeywords: [
      // Direct Tools, Music & Audio Generators
      'ai', 'suno', 'suno.ai', 'suno ai', 'suno v3', 'suno v4', 'suno v5', 'suno v6', 'suno studio',
      'udio', 'udio.ai', 'udio ai', 'udio v1', 'udio v1.5', 'udio v2',
      'elevenlabs', 'eleven labs', '11labs', 'fakeyou', 'uberduck', 'tortoise tts', 'rvc', 'rvc v2',
      'so-vits-svc', 'sovits', 'bark ai', 'voice clone', 'voice cloning', 'ai voice', 'ai vocals',
      'ai singer', 'ai cover', 'ai covers', 'ai duet', 'ai song', 'ai songs', 'ai rap', 'ai beat', 'ai beats',
      'ai track', 'ai tracks', 'ai audio', 'ai generated music', 'prompted music', 'riffusion', 'musicgen',
      // Celebrity / Character Voice Clones
      'ai drake', 'ai kanye', 'ai trump', 'ai biden', 'ai obama', 'ai spongebob', 'ai plankton',
      'ai michael jackson', 'ai freddie mercury', 'ai the weeknd', 'ai eminem', 'ai taylor swift',
      // Video, Animation & Diffusion
      'sora', 'sora 2', 'sora openai', 'runway', 'runwayml', 'gen-2', 'gen-3', 'gen-3 alpha', 'gen3 alpha',
      'kling', 'kling ai', 'kling 1.5', 'pika', 'pika labs', 'pika 1.0', 'pika 2.0', 'luma', 'luma ai',
      'dream machine', 'minimax', 'minimax video', 'hailuo', 'hailuo ai', 'haiper', 'haiper ai',
      'viggle', 'viggle ai', 'veo', 'google veo', 'ltx video', 'cogvideo', 'mochi 1', 'animatediff',
      'deforum', 'deforum stable diffusion', 'infinite zoom ai',
      'ai animation', 'ai animated', 'ai video', 'ai film', 'ai movie', 'ai cinema', 'ai trailer', 'ai visualizer',
      // Image & Art
      'midjourney', 'midjourney v5', 'midjourney v6', 'midjourney v7', 'dall-e', 'dall-e 3', 'dalle', 'dalle3',
      'stable diffusion', 'sdxl', 'sd1.5', 'sd3', 'flux.1', 'flux', 'flux dev', 'flux schnell',
      'comfyui', 'leonardo ai', 'ideogram', 'ideogram ai', 'magnific', 'magnific ai',
      'ai art', 'ai artwork', 'ai illustration',
      // Terminology & Disclosures
      'generative ai', 'gen ai', 'genai', 'ai generated', 'generated with ai', 'generated by ai',
      'made with ai', 'created with ai', 'created using ai', 'powered by ai', 'synthesized with ai',
      'deepfake', 'deep fake', 'synthetic media', 'synthetic voice', 'chatgpt', 'chat gpt', 'gpt-4', 'gpt-4o',
      'ai model', 'ai prompts', 'prompt sharing', 'prompt:', 'prompts shared',
      // Multilingual AI indicators
      'ki generiert', 'generado por ia', 'hecho con ia', 'généré par ia', 'создано ии', 'нейросеть',
      'ai生成', '画像生成ai', '音楽生成ai'
    ],
    customChannels: []
  };

  // Known / curated AI music & slop channels
  const CURATED_AI_CHANNELS = [
    'black pulse',
    'muzlub',
    'grandsound',
    'grand sound',
    'krya dark tech',
    'amoda session',
    'techno black',
    'nocturnal moon session',
    'hypnotic night sessions',
    'nocturne echoes',
    'nocturne echoes and nocturne cello',
    'dark noir techno',
    'wildcore techno',
    'shadow house mixes',
    'digital pulse beats',
    'obsidian hyper techno',
    'techno is my life',
    'cyber cyber',
    'dreamy darlings',
    'neurotune',
    'this song is ai',
    'the ai music genre dictionary',
    'ai mastery',
    'helio432hz',
    'studio suno',
    'suno hits',
    'suno music'
  ];

  // Automated content-farm SEO clickbait formula patterns
  const FARM_TITLE_PATTERNS = [
    /(?:202[4-9].*[🖤❤️⚫🐍🔥⚡💀🥀🎧✨⭐★].*(?:session|rave|mix|set|experience|descent|energy|horizons?)|[🖤❤️⚫🐍🔥⚡💀🥀🎧✨⭐★].*202[4-9].*(?:session|rave|mix|set|experience|descent|energy|horizons?))/i,
    /\b(?:peak time .* session|deep hypnotic .* experience|hypnotic underground .* (?:tech house|techno|house|rave|mix|set|experience|groove)|dark club bass|deep groove in .* forest|industrial warehouse .* (?:session|mix|set)|dark forest rave|toxic euphoria|beyond the (?:dark )?horizon|the rave lives inside you|the dark never forgets|what the darkness left behind|the night pulls you in|when .* meets .*(?:\[no ads\]|\(no ads\))|\[no ads\].*(?:mix|set|session|hours)|underground female dj|female dj drops the beat|cyber rave energy|industrial warehouse techno)\b/i,
    /\b(?:ai-generated tracks|generated by (?:suno|udio|ai)|made with (?:suno|udio)|suno ai showcase|suno studio|suno v[3-9]|udio v[1-9])\b/i,
    /\b(?:tech house|techno|deep house|trance|cyberpunk|synthwave)\s+202[4-9]\s*\|\s*[^|]+\|\s*[^|\n]+\b/i
  ];

  const FARM_CHANNEL_PATTERNS = [
    /\b(?:session|sessions|echoes|dark tech|pulse|pulse beats|sound lab|mixes|cybermode|music lab|records|beats lab)\b/i
  ];

  const CHATGPT_SNIPPET_PATTERNS = [
    /(?:the dark has a memory longer than yours|the walls are silent, but the rhythm is loud|some journeys change you\. this one doesn't ask permission|you didn't choose to come here\. the night pulled you in|some raves were never meant to be found|this is not just a mix; it's a high-voltage descent|dive into a deep hypnotic journey|step into a hypnotic journey|travel beyond the (?:dark )?horizon|welcome to a deep, dark and hypnotic|nocturnal moon session delivers|lose yourself in the (?:dark )?rhythm|let the bass take over|step into the dark forest|feel the atmosphere\. hear the bass|get lost in the groove|perfect for:.*late night drives|deep basslines, hypnotic rhythms|this mix creates a dark and cinematic vibe|warning: this mix may cause deep immersion|stay underground\. stay dark|expected deep bass|smooth and immersive, pulling you deeper|perfect for:.*(?:gym|drives|gaming|focus))/i
  ];

  // Channel name auto-AI regex
  const AI_CHANNEL_REGEX = /(?:^|\s|#|@|\b)(?:ai|suno|udio|midjourney|generative|deepfake|synthetics?|aimusic|aivideo)(?:\b|\s|$)/i;

  let compiledRegex = null;
  let flaggedCount = 0;

  // Helper for Unicode mathematical pseudo-font normalization (NFKD)
  function normalizeText(str) {
    if (!str) return '';
    return str.normalize('NFKD').replace(/[\u0300-\u036f]/g, '');
  }

  // Content ID & Music Distributor AI Footers
  const CONTENT_ID_AI_MUSIC_REGEX = /\b(?:provided to youtube by|auto-generated by youtube)\b[\s\S]*?\b(?:suno|udio|distrokid ai|amuse ai|landr ai)\b/i;

  // Shorts Speech & Facts Automation Formula
  const SHORTS_AUTOMATION_REGEX = /\b(?:what happens if|3 facts about|did you know that|unbelievable facts)\b.*#(?:shorts|ai|elevenlabs|aivoice|gpt4|voiceover)\b/i;

  // Emoji Clustering Formula
  const EMOJI_FARM_REGEX = /(?:[🖤❤️⚫🐍🔥⚡💀🥀🎧✨⭐★][\s]*){3,}/u;

  // Channel Handle Disposable Formula (@user-xxxxxxxx)
  const DISPOSABLE_HANDLE_REGEX = /^@user-[a-z0-9]{8,12}$/i;

  function compileKeywordRegex() {
    if (!config.customKeywords || config.customKeywords.length === 0) {
      compiledRegex = null;
      return;
    }
    const escaped = config.customKeywords
      .map(k => k.trim())
      .filter(k => k.length > 0)
      .map(k => {
        const bare = k.startsWith('#') ? k.slice(1) : k;
        const esc = bare.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        return `(?:#|\\b)${esc}\\b`;
      })
      .join('|');
    if (escaped) {
      compiledRegex = new RegExp(`(${escaped})`, 'i');
    } else {
      compiledRegex = null;
    }
  }

  // Selectors for video card containers across Home, Search, Watch Sidebar, and Shorts
  const CARD_SELECTORS = [
    'ytd-rich-item-renderer',       // Home page grid
    'ytd-video-renderer',           // Search results
    'ytd-compact-video-renderer',   // Watch page sidebar
    'ytd-grid-video-renderer',      // Channel tabs
    'ytd-playlist-video-renderer',  // Playlists
    'ytd-reel-video-renderer',      // Shorts in feed
    'ytd-rich-grid-slim-media'      // Shorts grid
  ].join(',');

  function checkCardForAI(card) {
    if (!config.enabled) return { isAI: false };

    // 1. Channel checks (Display Name & Handle URL)
    const channelInfo = getCardChannelInfo(card);
    const rawChannelName = channelInfo ? channelInfo.name : '';
    const rawChannelHandle = channelInfo && channelInfo.handle ? channelInfo.handle : '';

    const channelName = normalizeText(rawChannelName).toLowerCase();
    const channelHandle = normalizeText(rawChannelHandle).toLowerCase();

    if (channelName || channelHandle) {
      // User custom channel blacklist
      if (config.detectChannelList && config.customChannels && config.customChannels.length > 0) {
        for (const target of config.customChannels) {
          const lowerTarget = normalizeText(target).toLowerCase();
          if (
            (channelName && (channelName === lowerTarget || channelName.includes(lowerTarget) || lowerTarget.includes(channelName))) ||
            (channelHandle && (channelHandle === lowerTarget || channelHandle.includes(lowerTarget)))
          ) {
            return { isAI: true, reason: 'Blocked: ' + target, isBlocked: true };
          }
        }
      }

      // Curated Community AI channels
      if (config.enableCuratedList) {
        for (const known of CURATED_AI_CHANNELS) {
          if (channelName.includes(known) || channelHandle.includes(known.replace(/\s+/g, ''))) {
            return { isAI: true, reason: 'Curated AI Farm' };
          }
        }
      }

      // Automatic AI Channel Name / Handle Detection
      if (AI_CHANNEL_REGEX.test(channelName) || AI_CHANNEL_REGEX.test(channelHandle)) {
        return { isAI: true, reason: 'AI Channel' };
      }
    }

    // 2. Official YouTube Disclosure Badges (Altered or synthetic content)
    if (config.detectOfficialLabels) {
      const badges = card.querySelectorAll('ytd-badge-supported-renderer, .badge, .ytd-badge-supported-renderer, badge-shape, .yt-badge-shape, yt-icon-badge-shape, ytd-metadata-badge-renderer');
      for (const b of badges) {
        const text = normalizeText(b.textContent || b.getAttribute('aria-label') || '').toLowerCase();
        if (text.includes('synthetic') || text.includes('altered') || text.includes('made with ai') || text.includes('ai-generated') || text.includes('digitally generated')) {
          return { isAI: true, reason: 'YouTube AI Disclosure' };
        }
      }
    }

    // 3. Combined Title & Metadata Scan
    const titleEl = card.querySelector('#video-title, #video-title-link, h3, a#video-title');
    const rawTitle = titleEl ? titleEl.textContent : '';
    const titleText = normalizeText(rawTitle);
    const ariaText = normalizeText(titleEl ? (titleEl.getAttribute('aria-label') || titleEl.getAttribute('title') || '') : '');
    const descEl = card.querySelector('#description-text, .metadata-snippet-container, #snippet, ytd-video-meta-block, #description-inner');
    const descText = normalizeText(descEl ? descEl.textContent : '');
    const thumbImg = card.querySelector('ytd-thumbnail img, #thumbnail img');
    const thumbAlt = normalizeText(thumbImg ? (thumbImg.getAttribute('alt') || '') : '');
    const hashtags = normalizeText(Array.from(card.querySelectorAll('a[href*="/hashtag/"]')).map(a => a.textContent).join(' '));

    const combinedText = `${titleText} ${descText} ${ariaText} ${thumbAlt} ${hashtags} ${channelHandle}`;

    // Direct Keywords / Hashtags
    if (config.detectKeywords && compiledRegex) {
      const match = compiledRegex.exec(combinedText);
      if (match) {
        const found = (match[1] || match[0]).trim();
        return { isAI: true, reason: found.toUpperCase() };
      }
    }

    // Direct Content ID Music / Shorts Voiceover Automation regexes
    if (CONTENT_ID_AI_MUSIC_REGEX.test(descText)) {
      return { isAI: true, reason: 'Suno/Udio Content ID' };
    }
    if (SHORTS_AUTOMATION_REGEX.test(combinedText)) {
      return { isAI: true, reason: 'AI Shorts Voiceover' };
    }

    // 4. Content Farm Multi-Signal Weighted Heuristic Evaluation
    if (config.detectContentFarmPatterns) {
      let score = 0;

      // Check title farm patterns
      for (const tp of FARM_TITLE_PATTERNS) {
        if (tp.test(titleText)) {
          score += 50;
          break;
        }
      }

      // Check channel farm naming formula
      for (const cp of FARM_CHANNEL_PATTERNS) {
        if (cp.test(channelName)) {
          score += 35;
          break;
        }
      }

      // Check ChatGPT bio / description cliches
      if (descText) {
        for (const sp of CHATGPT_SNIPPET_PATTERNS) {
          if (sp.test(descText)) {
            score += 50;
            break;
          }
        }

        // Check DistroKid hyperfollow links without real tracklists
        if (/distrokid\.com\/hyperfollow/i.test(descText) && !/\b(?:0?1[:.-]|\b1\.\s)/i.test(descText)) {
          score += 45;
        }
      }

      // Check [No Ads] clickbait on hour mixes
      if (/\[no ads\]|\(no ads\)/i.test(titleText) && /\b(?:hour|hours|mix|techno|beats)\b/i.test(titleText)) {
        score += 25;
      }

      // Check Unicode Mathematical Stylized Font Evasion
      if (rawTitle !== titleText) {
        score += 25;
      }

      // Check Emoji Cluster
      if (EMOJI_FARM_REGEX.test(rawTitle)) {
        score += 20;
      }

      // Check Disposable Handle (@user-xxxxxxxx)
      if (DISPOSABLE_HANDLE_REGEX.test(channelHandle)) {
        score += 25;
      }

      if (score >= 45) {
        return { isAI: true, reason: 'AI Farm Heuristic' };
      }
    }

    return { isAI: false };
  }

  function getCardChannelInfo(card) {
    // 1. Search for channel links inside the card (e.g. /@DarkTechno, /channel/UC...)
    const channelLinks = card.querySelectorAll('a[href*="/@"], a[href*="/channel/"], ytd-channel-name a, #channel-name a, #byline a');
    for (const a of channelLinks) {
      const href = a.getAttribute('href') || '';
      if (href.startsWith('/watch') || href.startsWith('/playlist') || href.includes('/hashtag/')) continue;

      const name = a.textContent ? a.textContent.replace(/\s+/g, ' ').trim() : '';
      let handle = null;
      const handleMatch = href.match(/\/@([^\/?]+)/);
      if (handleMatch) {
        handle = '@' + handleMatch[1].toLowerCase();
      }

      if (name.length > 0 || handle) {
        return { name: name || handle, handle: handle };
      }
    }

    // 2. Fallback to channel text containers
    const el = card.querySelector('#channel-name #text, ytd-channel-name #text, .ytd-channel-name, #byline');
    if (el) {
      const lines = el.textContent.split('\n').map(s => s.trim()).filter(Boolean);
      if (lines.length > 0) {
        return { name: lines[0], handle: null };
      }
    }

    return null;
  }

  function handleBlockChannel(card) {
    const info = getCardChannelInfo(card);
    if (!info || !info.name) return;

    const channelName = info.name;
    const channelHandle = info.handle;
    const label = channelName || channelHandle;

    // Immediately collapse/hide this card on the page right now
    if (card.tagName.toLowerCase() === 'ytd-rich-item-renderer') {
      collapseGridCard(card, 'Blocked: ' + label);
    } else {
      card.classList.add('noai-hidden');
    }
    card.dataset.noaiState = `hide-Blocked: ${label}`;

    // Add to user custom channels list and persist
    let changed = false;
    const lowerName = channelName.toLowerCase();
    if (!config.customChannels.some(c => c.toLowerCase() === lowerName)) {
      config.customChannels.push(channelName);
      changed = true;
    }
    if (channelHandle && !config.customChannels.some(c => c.toLowerCase() === channelHandle.toLowerCase())) {
      config.customChannels.push(channelHandle);
      changed = true;
    }

    chrome.storage.sync.set({ customChannels: config.customChannels }, () => {
      processAllCards();
    });
    processAllCards();
  }

  function applyActionToCard(card, isAI, reason, isBlocked) {
    if (!isAI || !config.enabled) {
      if (card.dataset.noaiState) {
        card.classList.remove('noai-hidden', 'noai-collapsed', 'noai-blur');
        const badge = card.querySelector('.noai-badge-container');
        if (badge) badge.remove();
        const pill = card.querySelector('.noai-inline-pill');
        if (pill) pill.remove();
        const blockBtn = card.querySelector('.noai-block-btn');
        if (blockBtn) blockBtn.remove();
        const placeholder = card.querySelector('.noai-collapsed-placeholder');
        if (placeholder) placeholder.remove();
        delete card.dataset.noaiState;
      }
      return;
    }

    // Blocked channels are always hidden regardless of whether global action is tag or blur
    const effectiveAction = isBlocked ? 'hide' : config.action;
    const stateKey = `${effectiveAction}-${reason}`;

    // CRITICAL: If the card is already in the target state, do NOT remove or recreate DOM elements!
    // This stops the button from flickering/jumping and prevents click-through to YouTube thumbnail.
    if (card.dataset.noaiState === stateKey) {
      return;
    }
    card.dataset.noaiState = stateKey;

    if (effectiveAction === 'hide') {
      card.classList.remove('noai-blur');
      const existingBadge = card.querySelector('.noai-badge-container');
      if (existingBadge) existingBadge.remove();
      const existingBlockBtn = card.querySelector('.noai-block-btn');
      if (existingBlockBtn) existingBlockBtn.remove();

      if (card.tagName.toLowerCase() === 'ytd-rich-item-renderer') {
        collapseGridCard(card, reason);
      } else {
        card.classList.add('noai-hidden');
      }
    } else if (effectiveAction === 'blur') {
      card.classList.remove('noai-hidden', 'noai-collapsed');
      const placeholder = card.querySelector('.noai-collapsed-placeholder');
      if (placeholder) placeholder.remove();

      card.classList.add('noai-blur');
      addBadge(card, reason);
    } else {
      // Tag Mode: Big picture badge in corner + NO AI block button
      card.classList.remove('noai-hidden', 'noai-collapsed', 'noai-blur');
      const placeholder = card.querySelector('.noai-collapsed-placeholder');
      if (placeholder) placeholder.remove();

      addBadge(card, reason);
    }
  }

  function collapseGridCard(card, reason) {
    card.classList.add('noai-collapsed');
    
    if (!card.querySelector('.noai-collapsed-placeholder')) {
      const placeholder = document.createElement('div');
      placeholder.className = 'noai-collapsed-placeholder';
      
      const titleSpan = document.createElement('span');
      titleSpan.className = 'noai-placeholder-title';
      titleSpan.textContent = `🚫 AI Content Hidden (${reason})`;
      
      const unhideBtn = document.createElement('button');
      unhideBtn.className = 'noai-unhide-btn';
      unhideBtn.type = 'button';
      unhideBtn.title = 'View video';
      unhideBtn.textContent = 'Show';
      unhideBtn.addEventListener('click', (e) => {
        e.preventDefault();
        e.stopPropagation();
        card.classList.remove('noai-collapsed');
        placeholder.remove();
        delete card.dataset.noaiState;
        addBadge(card, reason);
      });

      placeholder.appendChild(titleSpan);
      placeholder.appendChild(unhideBtn);
      card.prepend(placeholder);
    }
  }

  function addBadge(card, reason) {
    // Anchor to thumbnail container (ytd-thumbnail or #thumbnail)
    const thumbContainer = card.querySelector('ytd-thumbnail, #thumbnail, .thumbnail-container');
    if (!thumbContainer) return;

    // Prefer attaching to outer container rather than link <a>
    let targetMount = thumbContainer;
    if (targetMount.tagName.toLowerCase() === 'a' && targetMount.parentElement) {
      targetMount = targetMount.parentElement;
    }

    const computedPos = window.getComputedStyle(targetMount).position;
    if (computedPos === 'static') {
      targetMount.style.position = 'relative';
    }

    // 1. Prominent AI Picture Badge in the Top-Right Corner (Inline SVG, 100% CSP immune)
    if (!targetMount.querySelector('.noai-badge-container')) {
      const badgeWrap = document.createElement('div');
      badgeWrap.className = 'noai-badge-container';
      badgeWrap.title = `Detected as AI: ${reason}`;
      badgeWrap.innerHTML = AI_BADGE_SVG;
      targetMount.appendChild(badgeWrap);
    }

    // 2. Inline Title Pill with Quick-Block button (placed outside <a> tags)
    if (!card.querySelector('.noai-inline-pill')) {
      const heading = card.querySelector('#title-wrapper, h3.title-and-badge, #meta, h3');
      const pill = document.createElement('div');
      pill.className = 'noai-inline-pill';

      const labelSpan = document.createElement('span');
      labelSpan.className = 'noai-pill-label';
      labelSpan.textContent = `⚡ AI: ${reason}`;

      const blockBtn = document.createElement('button');
      blockBtn.type = 'button';
      blockBtn.className = 'noai-pill-block-btn';
      blockBtn.title = 'Block this AI Channel permanently';
      blockBtn.textContent = '🚫 Block Channel';

      pill.appendChild(labelSpan);
      pill.appendChild(blockBtn);

      if (heading && heading.parentElement) {
        heading.parentElement.insertBefore(pill, heading);
      } else {
        const titleEl = card.querySelector('#video-title, #video-title-link, h3');
        if (titleEl && titleEl.parentElement) {
          titleEl.parentElement.insertBefore(pill, titleEl);
        }
      }
    }
  }

  // Delegated click listener: handles NoAI block buttons reliably without opening video
  document.addEventListener('click', (e) => {
    const pillBtn = e.target && e.target.closest ? e.target.closest('.noai-pill-block-btn') : null;
    if (pillBtn) {
      e.preventDefault();
      e.stopPropagation();
      e.stopImmediatePropagation();
      const card = pillBtn.closest(CARD_SELECTORS);
      if (card) {
        handleBlockChannel(card);
      }
    }
  }, true);

  // Stop pointer events on block button from triggering YouTube hover actions
  ['pointerdown', 'mousedown'].forEach(evt => {
    document.addEventListener(evt, (e) => {
      if (e.target && e.target.closest && e.target.closest('.noai-pill-block-btn, .noai-unhide-btn')) {
        e.preventDefault();
        e.stopPropagation();
      }
    }, true);
  });

  function processAllCards() {
    const cards = document.querySelectorAll(CARD_SELECTORS);
    let count = 0;

    cards.forEach(card => {
      const result = checkCardForAI(card);
      applyActionToCard(card, result.isAI, result.reason, result.isBlocked);
      if (result.isAI) {
        count++;
      }
    });

    if (count !== flaggedCount) {
      flaggedCount = count;
      try {
        chrome.runtime.sendMessage({ type: 'UPDATE_AI_COUNT', count: flaggedCount });
      } catch (e) {
        // Extension context might be invalidated during reload
      }
    }
  }

  // Watch page comprehensive AI detection & warning banner
  function checkWatchPage() {
    if (!location.pathname.startsWith('/watch')) {
      const existingBanner = document.getElementById('noai-watch-banner');
      if (existingBanner) existingBanner.remove();
      return;
    }

    if (!config.enabled) return;

    // Check watch page container or primary video metadata element
    const watchPrimary = document.querySelector('ytd-watch-flexy, #primary, #above-the-fold');
    if (!watchPrimary) return;

    // Evaluate watch page metadata using checkCardForAI logic
    const result = checkCardForAI(watchPrimary);

    const existingBanner = document.getElementById('noai-watch-banner');

    if (result.isAI) {
      if (!existingBanner) {
        const banner = document.createElement('div');
        banner.id = 'noai-watch-banner';
        banner.innerHTML = `
          <div class="noai-banner-content">
            <span class="noai-banner-icon">🤖</span>
            <div class="noai-banner-text">
              <strong>AI-Generated Video Detected</strong>
              <span class="noai-banner-reason">Reason: ${result.reason}</span>
            </div>
          </div>
          <div class="noai-banner-actions">
            <button class="noai-banner-block-btn" type="button" title="Block this AI Channel">🚫 Block Channel</button>
            <button class="noai-banner-close" type="button" title="Dismiss">&times;</button>
          </div>
        `;

        banner.querySelector('.noai-banner-close').addEventListener('click', () => banner.remove());
        
        const blockBtn = banner.querySelector('.noai-banner-block-btn');
        blockBtn.addEventListener('click', (e) => {
          e.preventDefault();
          e.stopPropagation();
          handleBlockChannel(watchPrimary);
          banner.remove();
        });

        const target = document.querySelector('#above-the-fold, #owner');
        if (target && target.parentElement) {
          target.parentElement.insertBefore(banner, target);
        }
      } else {
        // Update existing banner reason if needed
        const reasonEl = existingBanner.querySelector('.noai-banner-reason');
        if (reasonEl) {
          reasonEl.textContent = `Reason: ${result.reason}`;
        }
      }
    } else if (existingBanner) {
      existingBanner.remove();
    }
  }

  // Debounced scan for performance during scrolling
  let scanTimer = null;
  function scheduleScan() {
    if (scanTimer) clearTimeout(scanTimer);
    scanTimer = setTimeout(() => {
      processAllCards();
      checkWatchPage();
    }, 120);
  }

  // MutationObserver for infinite scroll & dynamic page loads
  const observer = new MutationObserver((mutations) => {
    let shouldScan = false;
    for (const m of mutations) {
      if (m.addedNodes.length > 0) {
        shouldScan = true;
        break;
      }
    }
    if (shouldScan) {
      scheduleScan();
    }
  });

  function startObserver() {
    const root = document.documentElement || document.body;
    if (root) {
      observer.observe(root, { childList: true, subtree: true });
    }
    setInterval(scheduleScan, 1500);
  }

  // Listen to configuration updates from Popup
  chrome.storage.onChanged.addListener((changes, area) => {
    if (area === 'sync' || area === 'local') {
      for (const [key, change] of Object.entries(changes)) {
        config[key] = change.newValue;
      }
      compileKeywordRegex();
      processAllCards();
      checkWatchPage();
    }
  });

  // YouTube SPA navigation listener
  window.addEventListener('yt-navigate-finish', () => {
    flaggedCount = 0;
    scheduleScan();
  });

  // Synchronous compilation of keywords
  compileKeywordRegex();

  function initObserver() {
    startObserver();
    scheduleScan();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initObserver);
  } else {
    initObserver();
  }

  window.addEventListener('load', scheduleScan);

  // Async load persisted settings
  try {
    if (chrome?.storage?.sync) {
      chrome.storage.sync.get(config, (stored) => {
        if (!chrome.runtime.lastError && stored) {
          config = { ...config, ...stored };
          compileKeywordRegex();
          scheduleScan();
        }
      });
    }
  } catch (e) {
    console.warn('[NoAI] Sync storage lookup skipped:', e);
  }
})();
