// Settings controller for NoAI popup

document.addEventListener('DOMContentLoaded', async () => {
  const masterToggle = document.getElementById('master-toggle');
  const actionRadios = document.querySelectorAll('input[name="action-choice"]');
  const detectOfficial = document.getElementById('detect-official');
  const detectKeywords = document.getElementById('detect-keywords');
  const detectCurated = document.getElementById('detect-curated');
  const detectHeuristics = document.getElementById('detect-heuristics');
  const enableQuickBlock = document.getElementById('enable-quick-block');
  const detectChannels = document.getElementById('detect-channels');
  const keywordsInput = document.getElementById('keywords-input');
  const channelsInput = document.getElementById('channels-input');
  const whitelistInput = document.getElementById('whitelist-input');
  const saveBtn = document.getElementById('save-advanced');
  const saveStatus = document.getElementById('save-status');

  // Load current values
  const data = await chrome.storage.sync.get({
    enabled: true,
    action: 'tag',
    detectOfficialLabels: true,
    detectKeywords: true,
    enableCuratedList: true,
    detectContentFarmPatterns: true,
    enableQuickBlockButton: true,
    detectChannelList: true,
    customKeywords: [
      // Direct Tools, Music & Audio Generators
      'ai', 'suno', 'suno.ai', 'suno ai', 'suno v3', 'suno v4', 'suno v5', 'suno v6', 'suno studio',
      'udio', 'udio.ai', 'udio ai', 'udio v1', 'udio v1.5', 'udio v2',
      'elevenlabs', 'eleven labs', '11labs', 'fakeyou', 'uberduck', 'tortoise tts', 'rvc', 'rvc v2',
      'so-vits-svc', 'sovits', 'bark ai', 'voice clone', 'voice cloning', 'ai voice', 'ai vocals',
      'ai singer', 'ai cover', 'ai covers', 'ai duet', 'ai song', 'ai songs', 'ai rap', 'ai beat', 'ai beats',
      'ai track', 'ai tracks', 'ai audio', 'ai generated music', 'prompted music', 'riffusion', 'musicgen',
      // Celebrity / Character Voice Clones
      'ai drake', 'ai kanye', 'ai trump', 'ai biden', 'ai obama', 'ai spongebob', 'ai plankton',
      'ai michael jackson', 'ai freddie mercury', 'ai the weeknd', 'ai eminem', 'ai taylor swift',
      // Video, Animation & Diffusion
      'sora', 'sora 2', 'sora openai', 'runway', 'runwayml', 'gen-2', 'gen-3', 'gen-3 alpha', 'gen3 alpha',
      'kling', 'kling ai', 'kling 1.5', 'pika', 'pika labs', 'pika 1.0', 'pika 2.0', 'luma', 'luma ai',
      'dream machine', 'minimax', 'minimax video', 'hailuo', 'hailuo ai', 'haiper', 'haiper ai',
      'viggle', 'viggle ai', 'veo', 'google veo', 'ltx video', 'cogvideo', 'mochi 1', 'animatediff',
      'deforum', 'deforum stable diffusion', 'infinite zoom ai',
      'ai animation', 'ai animated', 'ai video', 'ai film', 'ai movie', 'ai cinema', 'ai trailer', 'ai visualizer',
      // Image & Art
      'midjourney', 'midjourney v5', 'midjourney v6', 'midjourney v7', 'dall-e', 'dall-e 3', 'dalle', 'dalle3',
      'stable diffusion', 'sdxl', 'sd1.5', 'sd3', 'flux.1', 'flux', 'flux dev', 'flux schnell',
      'comfyui', 'leonardo ai', 'ideogram', 'ideogram ai', 'magnific', 'magnific ai',
      'ai art', 'ai artwork', 'ai illustration',
      // Terminology & Disclosures
      'generative ai', 'gen ai', 'genai', 'ai generated', 'generated with ai', 'generated by ai',
      'made with ai', 'created with ai', 'created using ai', 'powered by ai', 'synthesized with ai',
      'deepfake', 'deep fake', 'synthetic media', 'synthetic voice', 'chatgpt', 'chat gpt', 'gpt-4', 'gpt-4o',
      'ai model', 'ai prompts', 'prompt sharing', 'prompt:', 'prompts shared',
      // Multilingual AI indicators
      'ki generiert', 'generado por ia', 'hecho con ia', 'généré par ia', 'создано ии', 'нейросеть',
      'ai生成', '画像生成ai', '音楽生成ai'
    ],
    customChannels: [],
    whitelistedChannels: []
  });

  masterToggle.checked = data.enabled;
  detectOfficial.checked = data.detectOfficialLabels;
  detectKeywords.checked = data.detectKeywords;
  detectCurated.checked = data.enableCuratedList;
  detectHeuristics.checked = data.detectContentFarmPatterns;
  enableQuickBlock.checked = data.enableQuickBlockButton;
  detectChannels.checked = data.detectChannelList;

  actionRadios.forEach(radio => {
    if (radio.value === (data.action || 'tag')) {
      radio.checked = true;
    }
  });

  keywordsInput.value = (data.customKeywords || []).join(', ');
  channelsInput.value = (data.customChannels || []).join('\n');
  if (whitelistInput) {
    whitelistInput.value = (data.whitelistedChannels || []).join('\n');
  }

  // Immediate save on toggles
  masterToggle.addEventListener('change', async () => {
    await chrome.storage.sync.set({ enabled: masterToggle.checked });
  });

  actionRadios.forEach(radio => {
    radio.addEventListener('change', async () => {
      if (radio.checked) {
        await chrome.storage.sync.set({ action: radio.value });
      }
    });
  });

  detectOfficial.addEventListener('change', async () => {
    await chrome.storage.sync.set({ detectOfficialLabels: detectOfficial.checked });
  });

  detectKeywords.addEventListener('change', async () => {
    await chrome.storage.sync.set({ detectKeywords: detectKeywords.checked });
  });

  detectCurated.addEventListener('change', async () => {
    await chrome.storage.sync.set({ enableCuratedList: detectCurated.checked });
  });

  detectHeuristics.addEventListener('change', async () => {
    await chrome.storage.sync.set({ detectContentFarmPatterns: detectHeuristics.checked });
  });

  enableQuickBlock.addEventListener('change', async () => {
    await chrome.storage.sync.set({ enableQuickBlockButton: enableQuickBlock.checked });
  });

  detectChannels.addEventListener('change', async () => {
    await chrome.storage.sync.set({ detectChannelList: detectChannels.checked });
  });

  saveBtn.addEventListener('click', async () => {
    const rawKeywords = keywordsInput.value.split(',').map(s => s.trim()).filter(Boolean);
    const rawChannels = channelsInput.value.split('\n').map(s => s.trim()).filter(Boolean);
    const rawWhitelist = whitelistInput ? whitelistInput.value.split('\n').map(s => s.trim()).filter(Boolean) : [];

    await chrome.storage.sync.set({
      customKeywords: rawKeywords,
      customChannels: rawChannels,
      whitelistedChannels: rawWhitelist
    });

    saveStatus.textContent = 'Saved!';
    setTimeout(() => {
      saveStatus.textContent = '';
    }, 2000);
  });

  // Export Settings & Blocklist to JSON
  const exportBtn = document.getElementById('export-json');
  if (exportBtn) {
    exportBtn.addEventListener('click', async () => {
      const stored = await chrome.storage.sync.get(null);
      const jsonStr = JSON.stringify(stored, null, 2);
      const blob = new Blob([jsonStr], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `noai-youtube-settings-${new Date().toISOString().slice(0, 10)}.json`;
      a.click();
      URL.revokeObjectURL(url);
    });
  }

  // Import Settings & Blocklist from JSON
  const importBtn = document.getElementById('import-json');
  const importFile = document.getElementById('import-file');
  if (importBtn && importFile) {
    importBtn.addEventListener('click', () => importFile.click());
    importFile.addEventListener('change', (e) => {
      const file = e.target.files[0];
      if (!file) return;
      const reader = new FileReader();
      reader.onload = async (evt) => {
        try {
          const imported = JSON.parse(evt.target.result);
          if (imported && typeof imported === 'object') {
            await chrome.storage.sync.set(imported);
            saveStatus.textContent = 'Imported!';
            setTimeout(() => location.reload(), 1000);
          }
        } catch (err) {
          alert('Invalid JSON file format.');
        }
      };
      reader.readAsText(file);
    });
  }

  const donateLink = document.getElementById('donate-link');
  if (donateLink) {
    donateLink.addEventListener('click', (e) => {
      e.preventDefault();
      chrome.tabs.create({ url: donateLink.href });
    });
  }
});

