// Settings controller for NoAI popup

document.addEventListener('DOMContentLoaded', async () => {
  const masterToggle = document.getElementById('master-toggle');
  const actionRadios = document.querySelectorAll('input[name="action-choice"]');
  const detectOfficial = document.getElementById('detect-official');
  const detectKeywords = document.getElementById('detect-keywords');
  const detectCurated = document.getElementById('detect-curated');
  const detectHeuristics = document.getElementById('detect-heuristics');
  const enableQuickBlock = document.getElementById('enable-quick-block');
  const detectChannels = document.getElementById('detect-channels');
  const keywordsInput = document.getElementById('keywords-input');
  const channelsInput = document.getElementById('channels-input');
  const saveBtn = document.getElementById('save-advanced');
  const saveStatus = document.getElementById('save-status');

  // Load current values
  const data = await chrome.storage.sync.get({
    enabled: true,
    action: 'tag',
    detectOfficialLabels: true,
    detectKeywords: true,
    enableCuratedList: true,
    detectContentFarmPatterns: true,
    enableQuickBlockButton: true,
    detectChannelList: true,
    customKeywords: [
      // Direct Tools, Music & Audio Generators
      'suno', 'suno.ai', 'suno ai', 'suno v3', 'suno v3.5', 'suno v4', 'suno v5', 'suno v6', 'suno studio',
      'udio', 'udio.ai', 'udio ai', 'udio v1', 'udio v1.5', 'udio v2',
      'elevenlabs', 'eleven labs', '11labs', 'fakeyou', 'uberduck', 'tortoise tts', 'rvc', 'rvc v2',
      'so-vits-svc', 'sovits', 'bark ai', 'voice clone', 'voice cloning', 'ai voice', 'ai vocals',
      'ai singer', 'ai cover', 'ai covers', 'ai duet', 'ai song', 'ai songs', 'ai rap', 'ai beat', 'ai beats',
      'ai track', 'ai tracks', 'ai audio', 'ai generated music', 'ai generated song', 'prompted music', 'riffusion', 'musicgen',
      // Celebrity / Character Voice Clones
      'ai drake', 'ai kanye', 'ai trump', 'ai biden', 'ai obama', 'ai spongebob', 'ai plankton',
      'ai michael jackson', 'ai freddie mercury', 'ai the weeknd', 'ai eminem', 'ai taylor swift',
      // Video, Animation & Diffusion (Specific compound terms to avoid single-word FPs like flux, sora, luma, veo, kling)
      'sora 2', 'sora openai', 'sora ai', 'runwayml', 'gen-2', 'gen-3', 'gen-3 alpha', 'gen3 alpha',
      'kling ai', 'kling 1.5', 'pika labs', 'pika 1.0', 'pika 2.0', 'luma ai', 'luma dream machine',
      'minimax video', 'minimax ai', 'hailuo ai', 'hailuo 01', 'haiper ai', 'viggle ai', 'google veo', 'veo google',
      'ltx video', 'cogvideo', 'mochi 1', 'wan 2.1', 'wan2.1', 'hunyuan video', 'animatediff',
      'deforum stable diffusion', 'infinite zoom ai',
      'ai animation', 'ai animated video', 'ai film', 'ai movie', 'ai cinema', 'ai trailer', 'ai visualizer',
      // Image & Art
      'midjourney v5', 'midjourney v6', 'midjourney v7', 'dall-e 3', 'dalle3',
      'stable diffusion', 'sdxl', 'sd1.5', 'sd3', 'flux.1', 'flux dev', 'flux schnell', 'recraft',
      'comfyui', 'leonardo ai', 'ideogram ai', 'magnific ai',
      'ai art generator', 'ai artwork generator', 'ai illustration generator',
      // Terminology & Disclosures
      'generative ai music', 'ai generated video', 'ai generated track',
      'generated with ai', 'generated by ai', 'made with ai', 'created with ai', 'created using ai',
      'powered by ai', 'synthesized with ai', 'synthetic media', 'synthetic voice',
      'ai model prompt', 'prompts shared',
      // AI Generator Domains & Links
      'suno.com', 'udio.com', 'elevenlabs.io', 'midjourney.com', 'replicate.com/spaces',
      // Multilingual AI indicators
      'ki generiert', 'generado por ia', 'hecho con ia', 'généré par ia', 'создано ии', 'нейросеть',
      'ai生成', '画像生成ai', '音楽生成ai'
    ],
    customChannels: []
  });

  masterToggle.checked = data.enabled;
  detectOfficial.checked = data.detectOfficialLabels;
  detectKeywords.checked = data.detectKeywords;
  detectCurated.checked = data.enableCuratedList;
  detectHeuristics.checked = data.detectContentFarmPatterns;
  enableQuickBlock.checked = data.enableQuickBlockButton;
  detectChannels.checked = data.detectChannelList;

  actionRadios.forEach(radio => {
    if (radio.value === (data.action || 'tag')) {
      radio.checked = true;
    }
  });

  keywordsInput.value = (data.customKeywords || []).join(', ');
  channelsInput.value = (data.customChannels || []).join('\n');

  // Immediate save on toggles
  masterToggle.addEventListener('change', async () => {
    await chrome.storage.sync.set({ enabled: masterToggle.checked });
  });

  actionRadios.forEach(radio => {
    radio.addEventListener('change', async () => {
      if (radio.checked) {
        await chrome.storage.sync.set({ action: radio.value });
      }
    });
  });

  detectOfficial.addEventListener('change', async () => {
    await chrome.storage.sync.set({ detectOfficialLabels: detectOfficial.checked });
  });

  detectKeywords.addEventListener('change', async () => {
    await chrome.storage.sync.set({ detectKeywords: detectKeywords.checked });
  });

  detectCurated.addEventListener('change', async () => {
    await chrome.storage.sync.set({ enableCuratedList: detectCurated.checked });
  });

  detectHeuristics.addEventListener('change', async () => {
    await chrome.storage.sync.set({ detectContentFarmPatterns: detectHeuristics.checked });
  });

  enableQuickBlock.addEventListener('change', async () => {
    await chrome.storage.sync.set({ enableQuickBlockButton: enableQuickBlock.checked });
  });

  detectChannels.addEventListener('change', async () => {
    await chrome.storage.sync.set({ detectChannelList: detectChannels.checked });
  });

  saveBtn.addEventListener('click', async () => {
    const rawKeywords = keywordsInput.value.split(',').map(s => s.trim()).filter(Boolean);
    const rawChannels = channelsInput.value.split('\n').map(s => s.trim()).filter(Boolean);

    await chrome.storage.sync.set({
      customKeywords: rawKeywords,
      customChannels: rawChannels
    });

    saveStatus.textContent = 'Saved!';
    setTimeout(() => {
      saveStatus.textContent = '';
    }, 2000);
  });
});
